version: '3'

# ============== Variables ==============
vars:
  # Short git commit hash
  COMMIT_HASH:
    sh: git rev-parse --short HEAD
  # Latest tag version
  VERSION:
    sh: git describe --tags --abbrev=0
  # Go build flags with embedded version info
  GO_FLAGS: "-s -w -X main.CommitHash={{.COMMIT_HASH}} -X main.Version={{.VERSION}}"

  DEV_RUN_FLAGS: ""

# ============== Tasks ==============
tasks:

  # Build development binary
  build-dev:
    desc: "Build development binary for local testing"
    silent: true
    cmds:
      - echo "=== Building Development Binary ==="
      - |
        GOOS=linux \
        GOARCH=amd64 \
        go build -trimpath \
        -o "./fstmon-dev" \
        -v "./cmd/fstmon/main.go"
      - echo "=== Development Build Completed ==="


  # Run development binary
  run:
    desc: "Run development binary"
    silent: true
    deps: [build-dev]
    cmds:
      - echo "=== Running Development Binary ==="
      - ./fstmon-dev {{ .DEV_RUN_FLAGS }}
      - echo "=== Development Binary Finished ==="

