// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\rfstmon.common\x1a\tdto.proto2\xa3\x05\n" +
	"\x12MachineInfoService\x12K\n" +
	"\n" +
	"GetCpuInfo\x12\x1d.fstmon.dto.GetCpuInfoRequest\x1a\x1e.fstmon.dto.CpuPackageResponse\x12Q\n" +
	"\rGetCpuMetrics\x12 .fstmon.dto.GetCpuMetricsRequest\x1a\x1e.fstmon.dto.CpuMetricsResponse\x12W\n" +
	"\x0fGetInterfacesIO\x12\".fstmon.dto.GetInterfacesIORequest\x1a .fstmon.dto.InterfacesIOResponse\x12Q\n" +
	"\rGetSystemInfo\x12 .fstmon.dto.GetSystemInfoRequest\x1a\x1e.fstmon.dto.SystemInfoResponse\x12Z\n" +
	"\x10GetMemoryMetrics\x12#.fstmon.dto.GetMemoryMetricsRequest\x1a!.fstmon.dto.MemoryMetricsResponse\x12H\n" +
	"\n" +
	"GetThermal\x12\x1d.fstmon.dto.GetThermalRequest\x1a\x1b.fstmon.dto.ThermalResponse\x12Q\n" +
	"\rGetPartitions\x12 .fstmon.dto.GetPartitionsRequest\x1a\x1e.fstmon.dto.PartitionsResponse\x12H\n" +
	"\tGetDiskIO\x12\x1c.fstmon.dto.GetDiskIORequest\x1a\x1d.fstmon.dto.DiskIOMapResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var file_common_proto_goTypes = []any{
	(*GetCpuInfoRequest)(nil),       // 0: fstmon.dto.GetCpuInfoRequest
	(*GetCpuMetricsRequest)(nil),    // 1: fstmon.dto.GetCpuMetricsRequest
	(*GetInterfacesIORequest)(nil),  // 2: fstmon.dto.GetInterfacesIORequest
	(*GetSystemInfoRequest)(nil),    // 3: fstmon.dto.GetSystemInfoRequest
	(*GetMemoryMetricsRequest)(nil), // 4: fstmon.dto.GetMemoryMetricsRequest
	(*GetThermalRequest)(nil),       // 5: fstmon.dto.GetThermalRequest
	(*GetPartitionsRequest)(nil),    // 6: fstmon.dto.GetPartitionsRequest
	(*GetDiskIORequest)(nil),        // 7: fstmon.dto.GetDiskIORequest
	(*CpuPackageResponse)(nil),      // 8: fstmon.dto.CpuPackageResponse
	(*CpuMetricsResponse)(nil),      // 9: fstmon.dto.CpuMetricsResponse
	(*InterfacesIOResponse)(nil),    // 10: fstmon.dto.InterfacesIOResponse
	(*SystemInfoResponse)(nil),      // 11: fstmon.dto.SystemInfoResponse
	(*MemoryMetricsResponse)(nil),   // 12: fstmon.dto.MemoryMetricsResponse
	(*ThermalResponse)(nil),         // 13: fstmon.dto.ThermalResponse
	(*PartitionsResponse)(nil),      // 14: fstmon.dto.PartitionsResponse
	(*DiskIOMapResponse)(nil),       // 15: fstmon.dto.DiskIOMapResponse
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: fstmon.common.MachineInfoService.GetCpuInfo:input_type -> fstmon.dto.GetCpuInfoRequest
	1,  // 1: fstmon.common.MachineInfoService.GetCpuMetrics:input_type -> fstmon.dto.GetCpuMetricsRequest
	2,  // 2: fstmon.common.MachineInfoService.GetInterfacesIO:input_type -> fstmon.dto.GetInterfacesIORequest
	3,  // 3: fstmon.common.MachineInfoService.GetSystemInfo:input_type -> fstmon.dto.GetSystemInfoRequest
	4,  // 4: fstmon.common.MachineInfoService.GetMemoryMetrics:input_type -> fstmon.dto.GetMemoryMetricsRequest
	5,  // 5: fstmon.common.MachineInfoService.GetThermal:input_type -> fstmon.dto.GetThermalRequest
	6,  // 6: fstmon.common.MachineInfoService.GetPartitions:input_type -> fstmon.dto.GetPartitionsRequest
	7,  // 7: fstmon.common.MachineInfoService.GetDiskIO:input_type -> fstmon.dto.GetDiskIORequest
	8,  // 8: fstmon.common.MachineInfoService.GetCpuInfo:output_type -> fstmon.dto.CpuPackageResponse
	9,  // 9: fstmon.common.MachineInfoService.GetCpuMetrics:output_type -> fstmon.dto.CpuMetricsResponse
	10, // 10: fstmon.common.MachineInfoService.GetInterfacesIO:output_type -> fstmon.dto.InterfacesIOResponse
	11, // 11: fstmon.common.MachineInfoService.GetSystemInfo:output_type -> fstmon.dto.SystemInfoResponse
	12, // 12: fstmon.common.MachineInfoService.GetMemoryMetrics:output_type -> fstmon.dto.MemoryMetricsResponse
	13, // 13: fstmon.common.MachineInfoService.GetThermal:output_type -> fstmon.dto.ThermalResponse
	14, // 14: fstmon.common.MachineInfoService.GetPartitions:output_type -> fstmon.dto.PartitionsResponse
	15, // 15: fstmon.common.MachineInfoService.GetDiskIO:output_type -> fstmon.dto.DiskIOMapResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_dto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
