// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: common.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MachineInfoService_GetCpuInfo_FullMethodName       = "/fstmon.common.MachineInfoService/GetCpuInfo"
	MachineInfoService_GetCpuMetrics_FullMethodName    = "/fstmon.common.MachineInfoService/GetCpuMetrics"
	MachineInfoService_GetInterfacesIO_FullMethodName  = "/fstmon.common.MachineInfoService/GetInterfacesIO"
	MachineInfoService_GetSystemInfo_FullMethodName    = "/fstmon.common.MachineInfoService/GetSystemInfo"
	MachineInfoService_GetMemoryMetrics_FullMethodName = "/fstmon.common.MachineInfoService/GetMemoryMetrics"
	MachineInfoService_GetThermal_FullMethodName       = "/fstmon.common.MachineInfoService/GetThermal"
	MachineInfoService_GetPartitions_FullMethodName    = "/fstmon.common.MachineInfoService/GetPartitions"
	MachineInfoService_GetDiskIO_FullMethodName        = "/fstmon.common.MachineInfoService/GetDiskIO"
)

// MachineInfoServiceClient is the client API for MachineInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MachineInfoServiceClient interface {
	GetCpuInfo(ctx context.Context, in *GetCpuInfoRequest, opts ...grpc.CallOption) (*CpuPackageResponse, error)
	GetCpuMetrics(ctx context.Context, in *GetCpuMetricsRequest, opts ...grpc.CallOption) (*CpuMetricsResponse, error)
	GetInterfacesIO(ctx context.Context, in *GetInterfacesIORequest, opts ...grpc.CallOption) (*InterfacesIOResponse, error)
	GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
	GetMemoryMetrics(ctx context.Context, in *GetMemoryMetricsRequest, opts ...grpc.CallOption) (*MemoryMetricsResponse, error)
	GetThermal(ctx context.Context, in *GetThermalRequest, opts ...grpc.CallOption) (*ThermalResponse, error)
	GetPartitions(ctx context.Context, in *GetPartitionsRequest, opts ...grpc.CallOption) (*PartitionsResponse, error)
	GetDiskIO(ctx context.Context, in *GetDiskIORequest, opts ...grpc.CallOption) (*DiskIOMapResponse, error)
}

type machineInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMachineInfoServiceClient(cc grpc.ClientConnInterface) MachineInfoServiceClient {
	return &machineInfoServiceClient{cc}
}

func (c *machineInfoServiceClient) GetCpuInfo(ctx context.Context, in *GetCpuInfoRequest, opts ...grpc.CallOption) (*CpuPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuPackageResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetCpuInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetCpuMetrics(ctx context.Context, in *GetCpuMetricsRequest, opts ...grpc.CallOption) (*CpuMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuMetricsResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetCpuMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetInterfacesIO(ctx context.Context, in *GetInterfacesIORequest, opts ...grpc.CallOption) (*InterfacesIOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfacesIOResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetInterfacesIO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetSystemInfo(ctx context.Context, in *GetSystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfoResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetMemoryMetrics(ctx context.Context, in *GetMemoryMetricsRequest, opts ...grpc.CallOption) (*MemoryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryMetricsResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetMemoryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetThermal(ctx context.Context, in *GetThermalRequest, opts ...grpc.CallOption) (*ThermalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThermalResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetThermal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetPartitions(ctx context.Context, in *GetPartitionsRequest, opts ...grpc.CallOption) (*PartitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartitionsResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetPartitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *machineInfoServiceClient) GetDiskIO(ctx context.Context, in *GetDiskIORequest, opts ...grpc.CallOption) (*DiskIOMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskIOMapResponse)
	err := c.cc.Invoke(ctx, MachineInfoService_GetDiskIO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MachineInfoServiceServer is the server API for MachineInfoService service.
// All implementations must embed UnimplementedMachineInfoServiceServer
// for forward compatibility.
type MachineInfoServiceServer interface {
	GetCpuInfo(context.Context, *GetCpuInfoRequest) (*CpuPackageResponse, error)
	GetCpuMetrics(context.Context, *GetCpuMetricsRequest) (*CpuMetricsResponse, error)
	GetInterfacesIO(context.Context, *GetInterfacesIORequest) (*InterfacesIOResponse, error)
	GetSystemInfo(context.Context, *GetSystemInfoRequest) (*SystemInfoResponse, error)
	GetMemoryMetrics(context.Context, *GetMemoryMetricsRequest) (*MemoryMetricsResponse, error)
	GetThermal(context.Context, *GetThermalRequest) (*ThermalResponse, error)
	GetPartitions(context.Context, *GetPartitionsRequest) (*PartitionsResponse, error)
	GetDiskIO(context.Context, *GetDiskIORequest) (*DiskIOMapResponse, error)
	mustEmbedUnimplementedMachineInfoServiceServer()
}

// UnimplementedMachineInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMachineInfoServiceServer struct{}

func (UnimplementedMachineInfoServiceServer) GetCpuInfo(context.Context, *GetCpuInfoRequest) (*CpuPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpuInfo not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetCpuMetrics(context.Context, *GetCpuMetricsRequest) (*CpuMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpuMetrics not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetInterfacesIO(context.Context, *GetInterfacesIORequest) (*InterfacesIOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterfacesIO not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetSystemInfo(context.Context, *GetSystemInfoRequest) (*SystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetMemoryMetrics(context.Context, *GetMemoryMetricsRequest) (*MemoryMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemoryMetrics not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetThermal(context.Context, *GetThermalRequest) (*ThermalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThermal not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetPartitions(context.Context, *GetPartitionsRequest) (*PartitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartitions not implemented")
}
func (UnimplementedMachineInfoServiceServer) GetDiskIO(context.Context, *GetDiskIORequest) (*DiskIOMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiskIO not implemented")
}
func (UnimplementedMachineInfoServiceServer) mustEmbedUnimplementedMachineInfoServiceServer() {}
func (UnimplementedMachineInfoServiceServer) testEmbeddedByValue()                            {}

// UnsafeMachineInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MachineInfoServiceServer will
// result in compilation errors.
type UnsafeMachineInfoServiceServer interface {
	mustEmbedUnimplementedMachineInfoServiceServer()
}

func RegisterMachineInfoServiceServer(s grpc.ServiceRegistrar, srv MachineInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedMachineInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MachineInfoService_ServiceDesc, srv)
}

func _MachineInfoService_GetCpuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpuInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetCpuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetCpuInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetCpuInfo(ctx, req.(*GetCpuInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetCpuMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpuMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetCpuMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetCpuMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetCpuMetrics(ctx, req.(*GetCpuMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetInterfacesIO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterfacesIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetInterfacesIO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetInterfacesIO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetInterfacesIO(ctx, req.(*GetInterfacesIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetSystemInfo(ctx, req.(*GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetMemoryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetMemoryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetMemoryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetMemoryMetrics(ctx, req.(*GetMemoryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetThermal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThermalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetThermal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetThermal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetThermal(ctx, req.(*GetThermalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetPartitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetPartitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetPartitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetPartitions(ctx, req.(*GetPartitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MachineInfoService_GetDiskIO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiskIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MachineInfoServiceServer).GetDiskIO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MachineInfoService_GetDiskIO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MachineInfoServiceServer).GetDiskIO(ctx, req.(*GetDiskIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MachineInfoService_ServiceDesc is the grpc.ServiceDesc for MachineInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MachineInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fstmon.common.MachineInfoService",
	HandlerType: (*MachineInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCpuInfo",
			Handler:    _MachineInfoService_GetCpuInfo_Handler,
		},
		{
			MethodName: "GetCpuMetrics",
			Handler:    _MachineInfoService_GetCpuMetrics_Handler,
		},
		{
			MethodName: "GetInterfacesIO",
			Handler:    _MachineInfoService_GetInterfacesIO_Handler,
		},
		{
			MethodName: "GetSystemInfo",
			Handler:    _MachineInfoService_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetMemoryMetrics",
			Handler:    _MachineInfoService_GetMemoryMetrics_Handler,
		},
		{
			MethodName: "GetThermal",
			Handler:    _MachineInfoService_GetThermal_Handler,
		},
		{
			MethodName: "GetPartitions",
			Handler:    _MachineInfoService_GetPartitions_Handler,
		},
		{
			MethodName: "GetDiskIO",
			Handler:    _MachineInfoService_GetDiskIO_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
