// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IO for uint64
type IOUint64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       uint64                 `protobuf:"varint,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Rx            uint64                 `protobuf:"varint,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            uint64                 `protobuf:"varint,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOUint64) Reset() {
	*x = IOUint64{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOUint64) ProtoMessage() {}

func (x *IOUint64) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOUint64.ProtoReflect.Descriptor instead.
func (*IOUint64) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *IOUint64) GetSummary() uint64 {
	if x != nil {
		return x.Summary
	}
	return 0
}

func (x *IOUint64) GetRx() uint64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *IOUint64) GetTx() uint64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

// IO for float64
type IOFloat64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       float64                `protobuf:"fixed64,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Rx            float64                `protobuf:"fixed64,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            float64                `protobuf:"fixed64,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOFloat64) Reset() {
	*x = IOFloat64{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOFloat64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOFloat64) ProtoMessage() {}

func (x *IOFloat64) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOFloat64.ProtoReflect.Descriptor instead.
func (*IOFloat64) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *IOFloat64) GetSummary() float64 {
	if x != nil {
		return x.Summary
	}
	return 0
}

func (x *IOFloat64) GetRx() float64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *IOFloat64) GetTx() float64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

// IO for durations
type IODuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *durationpb.Duration   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Rx            *durationpb.Duration   `protobuf:"bytes,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            *durationpb.Duration   `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IODuration) Reset() {
	*x = IODuration{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IODuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IODuration) ProtoMessage() {}

func (x *IODuration) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IODuration.ProtoReflect.Descriptor instead.
func (*IODuration) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *IODuration) GetSummary() *durationpb.Duration {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *IODuration) GetRx() *durationpb.Duration {
	if x != nil {
		return x.Rx
	}
	return nil
}

func (x *IODuration) GetTx() *durationpb.Duration {
	if x != nil {
		return x.Tx
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\rfstmon.common\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\bIOUint64\x12\x18\n" +
	"\asummary\x18\x01 \x01(\x04R\asummary\x12\x0e\n" +
	"\x02rx\x18\x02 \x01(\x04R\x02rx\x12\x0e\n" +
	"\x02tx\x18\x03 \x01(\x04R\x02tx\"E\n" +
	"\tIOFloat64\x12\x18\n" +
	"\asummary\x18\x01 \x01(\x01R\asummary\x12\x0e\n" +
	"\x02rx\x18\x02 \x01(\x01R\x02rx\x12\x0e\n" +
	"\x02tx\x18\x03 \x01(\x01R\x02tx\"\x97\x01\n" +
	"\n" +
	"IODuration\x123\n" +
	"\asummary\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\asummary\x12)\n" +
	"\x02rx\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x02rx\x12)\n" +
	"\x02tx\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x02txB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(*IOUint64)(nil),            // 0: fstmon.common.IOUint64
	(*IOFloat64)(nil),           // 1: fstmon.common.IOFloat64
	(*IODuration)(nil),          // 2: fstmon.common.IODuration
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_common_proto_depIdxs = []int32{
	3, // 0: fstmon.common.IODuration.summary:type_name -> google.protobuf.Duration
	3, // 1: fstmon.common.IODuration.rx:type_name -> google.protobuf.Duration
	3, // 2: fstmon.common.IODuration.tx:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
