// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: cpu.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Static information about a CPU core
type CpuCoreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhysicalId    int32                  `protobuf:"varint,1,opt,name=physical_id,json=physicalId,proto3" json:"physical_id,omitempty"`
	CoreId        int32                  `protobuf:"varint,2,opt,name=core_id,json=coreId,proto3" json:"core_id,omitempty"`
	Siblings      int32                  `protobuf:"varint,3,opt,name=siblings,proto3" json:"siblings,omitempty"`
	CacheKb       int32                  `protobuf:"varint,4,opt,name=cache_kb,json=cacheKb,proto3" json:"cache_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuCoreInfo) Reset() {
	*x = CpuCoreInfo{}
	mi := &file_cpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuCoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuCoreInfo) ProtoMessage() {}

func (x *CpuCoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuCoreInfo.ProtoReflect.Descriptor instead.
func (*CpuCoreInfo) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{0}
}

func (x *CpuCoreInfo) GetPhysicalId() int32 {
	if x != nil {
		return x.PhysicalId
	}
	return 0
}

func (x *CpuCoreInfo) GetCoreId() int32 {
	if x != nil {
		return x.CoreId
	}
	return 0
}

func (x *CpuCoreInfo) GetSiblings() int32 {
	if x != nil {
		return x.Siblings
	}
	return 0
}

func (x *CpuCoreInfo) GetCacheKb() int32 {
	if x != nil {
		return x.CacheKb
	}
	return 0
}

// Static CPU package info
type CpuPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Microcode     string                 `protobuf:"bytes,3,opt,name=microcode,proto3" json:"microcode,omitempty"`
	Flags         []string               `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Cores         []*CpuCoreInfo         `protobuf:"bytes,5,rep,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuPackage) Reset() {
	*x = CpuPackage{}
	mi := &file_cpu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuPackage) ProtoMessage() {}

func (x *CpuPackage) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuPackage.ProtoReflect.Descriptor instead.
func (*CpuPackage) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{1}
}

func (x *CpuPackage) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *CpuPackage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CpuPackage) GetMicrocode() string {
	if x != nil {
		return x.Microcode
	}
	return ""
}

func (x *CpuPackage) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CpuPackage) GetCores() []*CpuCoreInfo {
	if x != nil {
		return x.Cores
	}
	return nil
}

// Dynamic per-core metrics
type CpuCoreMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load          float64                `protobuf:"fixed64,1,opt,name=load,proto3" json:"load,omitempty"`
	Frequency     float64                `protobuf:"fixed64,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuCoreMetrics) Reset() {
	*x = CpuCoreMetrics{}
	mi := &file_cpu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuCoreMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuCoreMetrics) ProtoMessage() {}

func (x *CpuCoreMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuCoreMetrics.ProtoReflect.Descriptor instead.
func (*CpuCoreMetrics) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{2}
}

func (x *CpuCoreMetrics) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *CpuCoreMetrics) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

// All CPU metrics
type CpuMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       *CpuCoreMetrics        `protobuf:"bytes,1,opt,name=average,proto3" json:"average,omitempty"`
	Cores         []*CpuCoreMetrics      `protobuf:"bytes,2,rep,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_cpu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{3}
}

func (x *CpuMetrics) GetAverage() *CpuCoreMetrics {
	if x != nil {
		return x.Average
	}
	return nil
}

func (x *CpuMetrics) GetCores() []*CpuCoreMetrics {
	if x != nil {
		return x.Cores
	}
	return nil
}

type GetCpuInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCpuInfoRequest) Reset() {
	*x = GetCpuInfoRequest{}
	mi := &file_cpu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpuInfoRequest) ProtoMessage() {}

func (x *GetCpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpuInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{4}
}

type GetCpuMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCpuMetricsRequest) Reset() {
	*x = GetCpuMetricsRequest{}
	mi := &file_cpu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCpuMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpuMetricsRequest) ProtoMessage() {}

func (x *GetCpuMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpuMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetCpuMetricsRequest) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{5}
}

type CpuPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CpuPackage            `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuPackageResponse) Reset() {
	*x = CpuPackageResponse{}
	mi := &file_cpu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuPackageResponse) ProtoMessage() {}

func (x *CpuPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuPackageResponse.ProtoReflect.Descriptor instead.
func (*CpuPackageResponse) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{6}
}

func (x *CpuPackageResponse) GetCpu() *CpuPackage {
	if x != nil {
		return x.Cpu
	}
	return nil
}

type CpuMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *CpuMetrics            `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetricsResponse) Reset() {
	*x = CpuMetricsResponse{}
	mi := &file_cpu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetricsResponse) ProtoMessage() {}

func (x *CpuMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetricsResponse.ProtoReflect.Descriptor instead.
func (*CpuMetricsResponse) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{7}
}

func (x *CpuMetricsResponse) GetMetrics() *CpuMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_cpu_proto protoreflect.FileDescriptor

const file_cpu_proto_rawDesc = "" +
	"\n" +
	"\tcpu.proto\x12\n" +
	"fstmon.cpu\x1a\fcommon.proto\"~\n" +
	"\vCpuCoreInfo\x12\x1f\n" +
	"\vphysical_id\x18\x01 \x01(\x05R\n" +
	"physicalId\x12\x17\n" +
	"\acore_id\x18\x02 \x01(\x05R\x06coreId\x12\x1a\n" +
	"\bsiblings\x18\x03 \x01(\x05R\bsiblings\x12\x19\n" +
	"\bcache_kb\x18\x04 \x01(\x05R\acacheKb\"\xa6\x01\n" +
	"\n" +
	"CpuPackage\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1c\n" +
	"\tmicrocode\x18\x03 \x01(\tR\tmicrocode\x12\x14\n" +
	"\x05flags\x18\x04 \x03(\tR\x05flags\x12-\n" +
	"\x05cores\x18\x05 \x03(\v2\x17.fstmon.cpu.CpuCoreInfoR\x05cores\"B\n" +
	"\x0eCpuCoreMetrics\x12\x12\n" +
	"\x04load\x18\x01 \x01(\x01R\x04load\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x01R\tfrequency\"t\n" +
	"\n" +
	"CpuMetrics\x124\n" +
	"\aaverage\x18\x01 \x01(\v2\x1a.fstmon.cpu.CpuCoreMetricsR\aaverage\x120\n" +
	"\x05cores\x18\x02 \x03(\v2\x1a.fstmon.cpu.CpuCoreMetricsR\x05cores\"\x13\n" +
	"\x11GetCpuInfoRequest\"\x16\n" +
	"\x14GetCpuMetricsRequest\">\n" +
	"\x12CpuPackageResponse\x12(\n" +
	"\x03cpu\x18\x01 \x01(\v2\x16.fstmon.cpu.CpuPackageR\x03cpu\"F\n" +
	"\x12CpuMetricsResponse\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.fstmon.cpu.CpuMetricsR\ametrics2\xac\x01\n" +
	"\n" +
	"CpuService\x12K\n" +
	"\n" +
	"GetCpuInfo\x12\x1d.fstmon.cpu.GetCpuInfoRequest\x1a\x1e.fstmon.cpu.CpuPackageResponse\x12Q\n" +
	"\rGetCpuMetrics\x12 .fstmon.cpu.GetCpuMetricsRequest\x1a\x1e.fstmon.cpu.CpuMetricsResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_cpu_proto_rawDescOnce sync.Once
	file_cpu_proto_rawDescData []byte
)

func file_cpu_proto_rawDescGZIP() []byte {
	file_cpu_proto_rawDescOnce.Do(func() {
		file_cpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cpu_proto_rawDesc), len(file_cpu_proto_rawDesc)))
	})
	return file_cpu_proto_rawDescData
}

var file_cpu_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cpu_proto_goTypes = []any{
	(*CpuCoreInfo)(nil),          // 0: fstmon.cpu.CpuCoreInfo
	(*CpuPackage)(nil),           // 1: fstmon.cpu.CpuPackage
	(*CpuCoreMetrics)(nil),       // 2: fstmon.cpu.CpuCoreMetrics
	(*CpuMetrics)(nil),           // 3: fstmon.cpu.CpuMetrics
	(*GetCpuInfoRequest)(nil),    // 4: fstmon.cpu.GetCpuInfoRequest
	(*GetCpuMetricsRequest)(nil), // 5: fstmon.cpu.GetCpuMetricsRequest
	(*CpuPackageResponse)(nil),   // 6: fstmon.cpu.CpuPackageResponse
	(*CpuMetricsResponse)(nil),   // 7: fstmon.cpu.CpuMetricsResponse
}
var file_cpu_proto_depIdxs = []int32{
	0, // 0: fstmon.cpu.CpuPackage.cores:type_name -> fstmon.cpu.CpuCoreInfo
	2, // 1: fstmon.cpu.CpuMetrics.average:type_name -> fstmon.cpu.CpuCoreMetrics
	2, // 2: fstmon.cpu.CpuMetrics.cores:type_name -> fstmon.cpu.CpuCoreMetrics
	1, // 3: fstmon.cpu.CpuPackageResponse.cpu:type_name -> fstmon.cpu.CpuPackage
	3, // 4: fstmon.cpu.CpuMetricsResponse.metrics:type_name -> fstmon.cpu.CpuMetrics
	4, // 5: fstmon.cpu.CpuService.GetCpuInfo:input_type -> fstmon.cpu.GetCpuInfoRequest
	5, // 6: fstmon.cpu.CpuService.GetCpuMetrics:input_type -> fstmon.cpu.GetCpuMetricsRequest
	6, // 7: fstmon.cpu.CpuService.GetCpuInfo:output_type -> fstmon.cpu.CpuPackageResponse
	7, // 8: fstmon.cpu.CpuService.GetCpuMetrics:output_type -> fstmon.cpu.CpuMetricsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cpu_proto_init() }
func file_cpu_proto_init() {
	if File_cpu_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cpu_proto_rawDesc), len(file_cpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cpu_proto_goTypes,
		DependencyIndexes: file_cpu_proto_depIdxs,
		MessageInfos:      file_cpu_proto_msgTypes,
	}.Build()
	File_cpu_proto = out.File
	file_cpu_proto_goTypes = nil
	file_cpu_proto_depIdxs = nil
}
