// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: cpu.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CpuService_GetCpuInfo_FullMethodName    = "/fstmon.cpu.CpuService/GetCpuInfo"
	CpuService_GetCpuMetrics_FullMethodName = "/fstmon.cpu.CpuService/GetCpuMetrics"
)

// CpuServiceClient is the client API for CpuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CpuServiceClient interface {
	GetCpuInfo(ctx context.Context, in *GetCpuInfoRequest, opts ...grpc.CallOption) (*CpuPackageResponse, error)
	GetCpuMetrics(ctx context.Context, in *GetCpuMetricsRequest, opts ...grpc.CallOption) (*CpuMetricsResponse, error)
}

type cpuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCpuServiceClient(cc grpc.ClientConnInterface) CpuServiceClient {
	return &cpuServiceClient{cc}
}

func (c *cpuServiceClient) GetCpuInfo(ctx context.Context, in *GetCpuInfoRequest, opts ...grpc.CallOption) (*CpuPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuPackageResponse)
	err := c.cc.Invoke(ctx, CpuService_GetCpuInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpuServiceClient) GetCpuMetrics(ctx context.Context, in *GetCpuMetricsRequest, opts ...grpc.CallOption) (*CpuMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpuMetricsResponse)
	err := c.cc.Invoke(ctx, CpuService_GetCpuMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CpuServiceServer is the server API for CpuService service.
// All implementations must embed UnimplementedCpuServiceServer
// for forward compatibility.
type CpuServiceServer interface {
	GetCpuInfo(context.Context, *GetCpuInfoRequest) (*CpuPackageResponse, error)
	GetCpuMetrics(context.Context, *GetCpuMetricsRequest) (*CpuMetricsResponse, error)
	mustEmbedUnimplementedCpuServiceServer()
}

// UnimplementedCpuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCpuServiceServer struct{}

func (UnimplementedCpuServiceServer) GetCpuInfo(context.Context, *GetCpuInfoRequest) (*CpuPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpuInfo not implemented")
}
func (UnimplementedCpuServiceServer) GetCpuMetrics(context.Context, *GetCpuMetricsRequest) (*CpuMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpuMetrics not implemented")
}
func (UnimplementedCpuServiceServer) mustEmbedUnimplementedCpuServiceServer() {}
func (UnimplementedCpuServiceServer) testEmbeddedByValue()                    {}

// UnsafeCpuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CpuServiceServer will
// result in compilation errors.
type UnsafeCpuServiceServer interface {
	mustEmbedUnimplementedCpuServiceServer()
}

func RegisterCpuServiceServer(s grpc.ServiceRegistrar, srv CpuServiceServer) {
	// If the following call panics, it indicates UnimplementedCpuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CpuService_ServiceDesc, srv)
}

func _CpuService_GetCpuInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpuInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpuServiceServer).GetCpuInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpuService_GetCpuInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpuServiceServer).GetCpuInfo(ctx, req.(*GetCpuInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpuService_GetCpuMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpuMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpuServiceServer).GetCpuMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpuService_GetCpuMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpuServiceServer).GetCpuMetrics(ctx, req.(*GetCpuMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CpuService_ServiceDesc is the grpc.ServiceDesc for CpuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CpuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fstmon.cpu.CpuService",
	HandlerType: (*CpuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCpuInfo",
			Handler:    _CpuService_GetCpuInfo_Handler,
		},
		{
			MethodName: "GetCpuMetrics",
			Handler:    _CpuService_GetCpuMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cpu.proto",
}
