// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: dto.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IO for uint64
type IOUint64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       uint64                 `protobuf:"varint,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Rx            uint64                 `protobuf:"varint,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            uint64                 `protobuf:"varint,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOUint64) Reset() {
	*x = IOUint64{}
	mi := &file_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOUint64) ProtoMessage() {}

func (x *IOUint64) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOUint64.ProtoReflect.Descriptor instead.
func (*IOUint64) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{0}
}

func (x *IOUint64) GetSummary() uint64 {
	if x != nil {
		return x.Summary
	}
	return 0
}

func (x *IOUint64) GetRx() uint64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *IOUint64) GetTx() uint64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

// IO for float64
type IOFloat64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       float64                `protobuf:"fixed64,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Rx            float64                `protobuf:"fixed64,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            float64                `protobuf:"fixed64,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOFloat64) Reset() {
	*x = IOFloat64{}
	mi := &file_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOFloat64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOFloat64) ProtoMessage() {}

func (x *IOFloat64) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOFloat64.ProtoReflect.Descriptor instead.
func (*IOFloat64) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{1}
}

func (x *IOFloat64) GetSummary() float64 {
	if x != nil {
		return x.Summary
	}
	return 0
}

func (x *IOFloat64) GetRx() float64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *IOFloat64) GetTx() float64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

// IO for durations
type IODuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *durationpb.Duration   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Rx            *durationpb.Duration   `protobuf:"bytes,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx            *durationpb.Duration   `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IODuration) Reset() {
	*x = IODuration{}
	mi := &file_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IODuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IODuration) ProtoMessage() {}

func (x *IODuration) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IODuration.ProtoReflect.Descriptor instead.
func (*IODuration) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{2}
}

func (x *IODuration) GetSummary() *durationpb.Duration {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *IODuration) GetRx() *durationpb.Duration {
	if x != nil {
		return x.Rx
	}
	return nil
}

func (x *IODuration) GetTx() *durationpb.Duration {
	if x != nil {
		return x.Tx
	}
	return nil
}

type CpuCoreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhysicalId    int32                  `protobuf:"varint,1,opt,name=physical_id,json=physicalId,proto3" json:"physical_id,omitempty"`
	CoreId        int32                  `protobuf:"varint,2,opt,name=core_id,json=coreId,proto3" json:"core_id,omitempty"`
	Siblings      int32                  `protobuf:"varint,3,opt,name=siblings,proto3" json:"siblings,omitempty"`
	CacheKb       int32                  `protobuf:"varint,4,opt,name=cache_kb,json=cacheKb,proto3" json:"cache_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuCoreInfo) Reset() {
	*x = CpuCoreInfo{}
	mi := &file_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuCoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuCoreInfo) ProtoMessage() {}

func (x *CpuCoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuCoreInfo.ProtoReflect.Descriptor instead.
func (*CpuCoreInfo) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{3}
}

func (x *CpuCoreInfo) GetPhysicalId() int32 {
	if x != nil {
		return x.PhysicalId
	}
	return 0
}

func (x *CpuCoreInfo) GetCoreId() int32 {
	if x != nil {
		return x.CoreId
	}
	return 0
}

func (x *CpuCoreInfo) GetSiblings() int32 {
	if x != nil {
		return x.Siblings
	}
	return 0
}

func (x *CpuCoreInfo) GetCacheKb() int32 {
	if x != nil {
		return x.CacheKb
	}
	return 0
}

type CpuPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Microcode     string                 `protobuf:"bytes,3,opt,name=microcode,proto3" json:"microcode,omitempty"`
	Flags         []string               `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	Cores         []*CpuCoreInfo         `protobuf:"bytes,5,rep,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuPackage) Reset() {
	*x = CpuPackage{}
	mi := &file_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuPackage) ProtoMessage() {}

func (x *CpuPackage) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuPackage.ProtoReflect.Descriptor instead.
func (*CpuPackage) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{4}
}

func (x *CpuPackage) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *CpuPackage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CpuPackage) GetMicrocode() string {
	if x != nil {
		return x.Microcode
	}
	return ""
}

func (x *CpuPackage) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CpuPackage) GetCores() []*CpuCoreInfo {
	if x != nil {
		return x.Cores
	}
	return nil
}

type CpuCoreMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load          float64                `protobuf:"fixed64,1,opt,name=load,proto3" json:"load,omitempty"`
	Frequency     float64                `protobuf:"fixed64,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuCoreMetrics) Reset() {
	*x = CpuCoreMetrics{}
	mi := &file_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuCoreMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuCoreMetrics) ProtoMessage() {}

func (x *CpuCoreMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuCoreMetrics.ProtoReflect.Descriptor instead.
func (*CpuCoreMetrics) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{5}
}

func (x *CpuCoreMetrics) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *CpuCoreMetrics) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type CpuMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       *CpuCoreMetrics        `protobuf:"bytes,1,opt,name=average,proto3" json:"average,omitempty"`
	Cores         []*CpuCoreMetrics      `protobuf:"bytes,2,rep,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetrics) Reset() {
	*x = CpuMetrics{}
	mi := &file_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetrics) ProtoMessage() {}

func (x *CpuMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetrics.ProtoReflect.Descriptor instead.
func (*CpuMetrics) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{6}
}

func (x *CpuMetrics) GetAverage() *CpuCoreMetrics {
	if x != nil {
		return x.Average
	}
	return nil
}

func (x *CpuMetrics) GetCores() []*CpuCoreMetrics {
	if x != nil {
		return x.Cores
	}
	return nil
}

type GetCpuInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCpuInfoRequest) Reset() {
	*x = GetCpuInfoRequest{}
	mi := &file_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpuInfoRequest) ProtoMessage() {}

func (x *GetCpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpuInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{7}
}

type GetCpuMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCpuMetricsRequest) Reset() {
	*x = GetCpuMetricsRequest{}
	mi := &file_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCpuMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpuMetricsRequest) ProtoMessage() {}

func (x *GetCpuMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpuMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetCpuMetricsRequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{8}
}

type CpuPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CpuPackage            `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuPackageResponse) Reset() {
	*x = CpuPackageResponse{}
	mi := &file_dto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuPackageResponse) ProtoMessage() {}

func (x *CpuPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuPackageResponse.ProtoReflect.Descriptor instead.
func (*CpuPackageResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{9}
}

func (x *CpuPackageResponse) GetCpu() *CpuPackage {
	if x != nil {
		return x.Cpu
	}
	return nil
}

type CpuMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *CpuMetrics            `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuMetricsResponse) Reset() {
	*x = CpuMetricsResponse{}
	mi := &file_dto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuMetricsResponse) ProtoMessage() {}

func (x *CpuMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuMetricsResponse.ProtoReflect.Descriptor instead.
func (*CpuMetricsResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{10}
}

func (x *CpuMetricsResponse) GetMetrics() *CpuMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type InterfaceIO struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BytesTotal        *IOUint64              `protobuf:"bytes,1,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	PacketsTotal      *IOUint64              `protobuf:"bytes,2,opt,name=packets_total,json=packetsTotal,proto3" json:"packets_total,omitempty"`
	ErrorPacketsTotal *IOUint64              `protobuf:"bytes,3,opt,name=error_packets_total,json=errorPacketsTotal,proto3" json:"error_packets_total,omitempty"`
	DropPacketsTotal  *IOUint64              `protobuf:"bytes,4,opt,name=drop_packets_total,json=dropPacketsTotal,proto3" json:"drop_packets_total,omitempty"`
	BytesPerSec       *IOUint64              `protobuf:"bytes,5,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	PacketsPerSec     *IOUint64              `protobuf:"bytes,6,opt,name=packets_per_sec,json=packetsPerSec,proto3" json:"packets_per_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InterfaceIO) Reset() {
	*x = InterfaceIO{}
	mi := &file_dto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceIO) ProtoMessage() {}

func (x *InterfaceIO) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceIO.ProtoReflect.Descriptor instead.
func (*InterfaceIO) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{11}
}

func (x *InterfaceIO) GetBytesTotal() *IOUint64 {
	if x != nil {
		return x.BytesTotal
	}
	return nil
}

func (x *InterfaceIO) GetPacketsTotal() *IOUint64 {
	if x != nil {
		return x.PacketsTotal
	}
	return nil
}

func (x *InterfaceIO) GetErrorPacketsTotal() *IOUint64 {
	if x != nil {
		return x.ErrorPacketsTotal
	}
	return nil
}

func (x *InterfaceIO) GetDropPacketsTotal() *IOUint64 {
	if x != nil {
		return x.DropPacketsTotal
	}
	return nil
}

func (x *InterfaceIO) GetBytesPerSec() *IOUint64 {
	if x != nil {
		return x.BytesPerSec
	}
	return nil
}

func (x *InterfaceIO) GetPacketsPerSec() *IOUint64 {
	if x != nil {
		return x.PacketsPerSec
	}
	return nil
}

type InterfacesIO struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Interfaces    map[string]*InterfaceIO `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesIO) Reset() {
	*x = InterfacesIO{}
	mi := &file_dto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesIO) ProtoMessage() {}

func (x *InterfacesIO) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesIO.ProtoReflect.Descriptor instead.
func (*InterfacesIO) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{12}
}

func (x *InterfacesIO) GetInterfaces() map[string]*InterfaceIO {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type GetInterfacesIORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfacesIORequest) Reset() {
	*x = GetInterfacesIORequest{}
	mi := &file_dto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfacesIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfacesIORequest) ProtoMessage() {}

func (x *GetInterfacesIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfacesIORequest.ProtoReflect.Descriptor instead.
func (*GetInterfacesIORequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{13}
}

type InterfacesIOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *InterfacesIO          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesIOResponse) Reset() {
	*x = InterfacesIOResponse{}
	mi := &file_dto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesIOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesIOResponse) ProtoMessage() {}

func (x *InterfacesIOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesIOResponse.ProtoReflect.Descriptor instead.
func (*InterfacesIOResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{14}
}

func (x *InterfacesIOResponse) GetData() *InterfacesIO {
	if x != nil {
		return x.Data
	}
	return nil
}

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        *durationpb.Duration   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Idle          *durationpb.Duration   `protobuf:"bytes,2,opt,name=idle,proto3" json:"idle,omitempty"`
	Load1         float64                `protobuf:"fixed64,3,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,4,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,5,opt,name=load15,proto3" json:"load15,omitempty"`
	RunningProcs  int32                  `protobuf:"varint,6,opt,name=running_procs,json=runningProcs,proto3" json:"running_procs,omitempty"`
	TotalProcs    int32                  `protobuf:"varint,7,opt,name=total_procs,json=totalProcs,proto3" json:"total_procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_dto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{15}
}

func (x *SystemInfo) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *SystemInfo) GetIdle() *durationpb.Duration {
	if x != nil {
		return x.Idle
	}
	return nil
}

func (x *SystemInfo) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *SystemInfo) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *SystemInfo) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *SystemInfo) GetRunningProcs() int32 {
	if x != nil {
		return x.RunningProcs
	}
	return 0
}

func (x *SystemInfo) GetTotalProcs() int32 {
	if x != nil {
		return x.TotalProcs
	}
	return 0
}

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_dto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{16}
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *SystemInfo            `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_dto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{17}
}

func (x *SystemInfoResponse) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

type MemoryMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Total           uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available       uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Used            uint64                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Free            uint64                 `protobuf:"varint,4,opt,name=free,proto3" json:"free,omitempty"`
	SwapTotal       uint64                 `protobuf:"varint,5,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapAvailable   uint64                 `protobuf:"varint,6,opt,name=swap_available,json=swapAvailable,proto3" json:"swap_available,omitempty"`
	SwapUsed        uint64                 `protobuf:"varint,7,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree        uint64                 `protobuf:"varint,8,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	UsedPercent     float64                `protobuf:"fixed64,9,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	SwapUsedPercent float64                `protobuf:"fixed64,10,opt,name=swap_used_percent,json=swapUsedPercent,proto3" json:"swap_used_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_dto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{18}
}

func (x *MemoryMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryMetrics) GetSwapAvailable() uint64 {
	if x != nil {
		return x.SwapAvailable
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MemoryMetrics) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *MemoryMetrics) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsedPercent() float64 {
	if x != nil {
		return x.SwapUsedPercent
	}
	return 0
}

type GetMemoryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryMetricsRequest) Reset() {
	*x = GetMemoryMetricsRequest{}
	mi := &file_dto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryMetricsRequest) ProtoMessage() {}

func (x *GetMemoryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{19}
}

type MemoryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryMetrics         `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetricsResponse) Reset() {
	*x = MemoryMetricsResponse{}
	mi := &file_dto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetricsResponse) ProtoMessage() {}

func (x *MemoryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetricsResponse.ProtoReflect.Descriptor instead.
func (*MemoryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{20}
}

func (x *MemoryMetricsResponse) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

type ThermalMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       float64                `protobuf:"fixed64,1,opt,name=current,proto3" json:"current,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Crit          float64                `protobuf:"fixed64,3,opt,name=crit,proto3" json:"crit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThermalMetrics) Reset() {
	*x = ThermalMetrics{}
	mi := &file_dto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalMetrics) ProtoMessage() {}

func (x *ThermalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalMetrics.ProtoReflect.Descriptor instead.
func (*ThermalMetrics) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{21}
}

func (x *ThermalMetrics) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ThermalMetrics) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ThermalMetrics) GetCrit() float64 {
	if x != nil {
		return x.Crit
	}
	return 0
}

type ThermalMetricsMap struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sensors       map[string]*ThermalMetrics `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThermalMetricsMap) Reset() {
	*x = ThermalMetricsMap{}
	mi := &file_dto_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalMetricsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalMetricsMap) ProtoMessage() {}

func (x *ThermalMetricsMap) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalMetricsMap.ProtoReflect.Descriptor instead.
func (*ThermalMetricsMap) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{22}
}

func (x *ThermalMetricsMap) GetSensors() map[string]*ThermalMetrics {
	if x != nil {
		return x.Sensors
	}
	return nil
}

type GetThermalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThermalRequest) Reset() {
	*x = GetThermalRequest{}
	mi := &file_dto_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThermalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThermalRequest) ProtoMessage() {}

func (x *GetThermalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThermalRequest.ProtoReflect.Descriptor instead.
func (*GetThermalRequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{23}
}

type ThermalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *ThermalMetricsMap     `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThermalResponse) Reset() {
	*x = ThermalResponse{}
	mi := &file_dto_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalResponse) ProtoMessage() {}

func (x *ThermalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalResponse.ProtoReflect.Descriptor instead.
func (*ThermalResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{24}
}

func (x *ThermalResponse) GetMetrics() *ThermalMetricsMap {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PartitionUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Total             uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used              uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free              uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent       float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	InodesTotal       uint64                 `protobuf:"varint,5,opt,name=inodes_total,json=inodesTotal,proto3" json:"inodes_total,omitempty"`
	InodesUsed        uint64                 `protobuf:"varint,6,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	InodesFree        uint64                 `protobuf:"varint,7,opt,name=inodes_free,json=inodesFree,proto3" json:"inodes_free,omitempty"`
	InodesUsedPercent float64                `protobuf:"fixed64,8,opt,name=inodes_used_percent,json=inodesUsedPercent,proto3" json:"inodes_used_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PartitionUsage) Reset() {
	*x = PartitionUsage{}
	mi := &file_dto_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionUsage) ProtoMessage() {}

func (x *PartitionUsage) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionUsage.ProtoReflect.Descriptor instead.
func (*PartitionUsage) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{25}
}

func (x *PartitionUsage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PartitionUsage) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *PartitionUsage) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *PartitionUsage) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *PartitionUsage) GetInodesTotal() uint64 {
	if x != nil {
		return x.InodesTotal
	}
	return 0
}

func (x *PartitionUsage) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *PartitionUsage) GetInodesFree() uint64 {
	if x != nil {
		return x.InodesFree
	}
	return 0
}

func (x *PartitionUsage) GetInodesUsedPercent() float64 {
	if x != nil {
		return x.InodesUsedPercent
	}
	return 0
}

type Partition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mount         string                 `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	Filesystem    string                 `protobuf:"bytes,3,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Usage         *PartitionUsage        `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_dto_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{26}
}

func (x *Partition) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Partition) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Partition) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Partition) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Partition) GetUsage() *PartitionUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Partitions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*Partition           `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partitions) Reset() {
	*x = Partitions{}
	mi := &file_dto_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partitions) ProtoMessage() {}

func (x *Partitions) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partitions.ProtoReflect.Descriptor instead.
func (*Partitions) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{27}
}

func (x *Partitions) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type DiskIO struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IopsInProgress  uint64                 `protobuf:"varint,1,opt,name=iops_in_progress,json=iopsInProgress,proto3" json:"iops_in_progress,omitempty"`
	Ops             *IOUint64              `protobuf:"bytes,2,opt,name=ops,proto3" json:"ops,omitempty"`
	MergedOps       *IOUint64              `protobuf:"bytes,3,opt,name=merged_ops,json=mergedOps,proto3" json:"merged_ops,omitempty"`
	Bytes           *IOUint64              `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	OpsPerSec       *IOUint64              `protobuf:"bytes,5,opt,name=ops_per_sec,json=opsPerSec,proto3" json:"ops_per_sec,omitempty"`
	MergedOpsPerSec *IOUint64              `protobuf:"bytes,6,opt,name=merged_ops_per_sec,json=mergedOpsPerSec,proto3" json:"merged_ops_per_sec,omitempty"`
	BytesPerSec     *IOUint64              `protobuf:"bytes,7,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	Time            *IODuration            `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	IoTime          *durationpb.Duration   `protobuf:"bytes,9,opt,name=io_time,json=ioTime,proto3" json:"io_time,omitempty"`
	WeightedIo      *durationpb.Duration   `protobuf:"bytes,10,opt,name=weighted_io,json=weightedIo,proto3" json:"weighted_io,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiskIO) Reset() {
	*x = DiskIO{}
	mi := &file_dto_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIO) ProtoMessage() {}

func (x *DiskIO) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIO.ProtoReflect.Descriptor instead.
func (*DiskIO) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{28}
}

func (x *DiskIO) GetIopsInProgress() uint64 {
	if x != nil {
		return x.IopsInProgress
	}
	return 0
}

func (x *DiskIO) GetOps() *IOUint64 {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *DiskIO) GetMergedOps() *IOUint64 {
	if x != nil {
		return x.MergedOps
	}
	return nil
}

func (x *DiskIO) GetBytes() *IOUint64 {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *DiskIO) GetOpsPerSec() *IOUint64 {
	if x != nil {
		return x.OpsPerSec
	}
	return nil
}

func (x *DiskIO) GetMergedOpsPerSec() *IOUint64 {
	if x != nil {
		return x.MergedOpsPerSec
	}
	return nil
}

func (x *DiskIO) GetBytesPerSec() *IOUint64 {
	if x != nil {
		return x.BytesPerSec
	}
	return nil
}

func (x *DiskIO) GetTime() *IODuration {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DiskIO) GetIoTime() *durationpb.Duration {
	if x != nil {
		return x.IoTime
	}
	return nil
}

func (x *DiskIO) GetWeightedIo() *durationpb.Duration {
	if x != nil {
		return x.WeightedIo
	}
	return nil
}

type DiskIOMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         map[string]*DiskIO     `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIOMap) Reset() {
	*x = DiskIOMap{}
	mi := &file_dto_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIOMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIOMap) ProtoMessage() {}

func (x *DiskIOMap) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIOMap.ProtoReflect.Descriptor instead.
func (*DiskIOMap) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{29}
}

func (x *DiskIOMap) GetDisks() map[string]*DiskIO {
	if x != nil {
		return x.Disks
	}
	return nil
}

type GetPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionsRequest) Reset() {
	*x = GetPartitionsRequest{}
	mi := &file_dto_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionsRequest) ProtoMessage() {}

func (x *GetPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionsRequest.ProtoReflect.Descriptor instead.
func (*GetPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{30}
}

type GetDiskIORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskIORequest) Reset() {
	*x = GetDiskIORequest{}
	mi := &file_dto_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskIORequest) ProtoMessage() {}

func (x *GetDiskIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskIORequest.ProtoReflect.Descriptor instead.
func (*GetDiskIORequest) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{31}
}

type PartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    *Partitions            `protobuf:"bytes,1,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionsResponse) Reset() {
	*x = PartitionsResponse{}
	mi := &file_dto_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionsResponse) ProtoMessage() {}

func (x *PartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionsResponse.ProtoReflect.Descriptor instead.
func (*PartitionsResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{32}
}

func (x *PartitionsResponse) GetPartitions() *Partitions {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type DiskIOMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Io            *DiskIOMap             `protobuf:"bytes,1,opt,name=io,proto3" json:"io,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIOMapResponse) Reset() {
	*x = DiskIOMapResponse{}
	mi := &file_dto_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIOMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIOMapResponse) ProtoMessage() {}

func (x *DiskIOMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dto_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIOMapResponse.ProtoReflect.Descriptor instead.
func (*DiskIOMapResponse) Descriptor() ([]byte, []int) {
	return file_dto_proto_rawDescGZIP(), []int{33}
}

func (x *DiskIOMapResponse) GetIo() *DiskIOMap {
	if x != nil {
		return x.Io
	}
	return nil
}

var File_dto_proto protoreflect.FileDescriptor

const file_dto_proto_rawDesc = "" +
	"\n" +
	"\tdto.proto\x12\n" +
	"fstmon.dto\x1a\x1egoogle/protobuf/duration.proto\"D\n" +
	"\bIOUint64\x12\x18\n" +
	"\asummary\x18\x01 \x01(\x04R\asummary\x12\x0e\n" +
	"\x02rx\x18\x02 \x01(\x04R\x02rx\x12\x0e\n" +
	"\x02tx\x18\x03 \x01(\x04R\x02tx\"E\n" +
	"\tIOFloat64\x12\x18\n" +
	"\asummary\x18\x01 \x01(\x01R\asummary\x12\x0e\n" +
	"\x02rx\x18\x02 \x01(\x01R\x02rx\x12\x0e\n" +
	"\x02tx\x18\x03 \x01(\x01R\x02tx\"\x97\x01\n" +
	"\n" +
	"IODuration\x123\n" +
	"\asummary\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\asummary\x12)\n" +
	"\x02rx\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x02rx\x12)\n" +
	"\x02tx\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x02tx\"~\n" +
	"\vCpuCoreInfo\x12\x1f\n" +
	"\vphysical_id\x18\x01 \x01(\x05R\n" +
	"physicalId\x12\x17\n" +
	"\acore_id\x18\x02 \x01(\x05R\x06coreId\x12\x1a\n" +
	"\bsiblings\x18\x03 \x01(\x05R\bsiblings\x12\x19\n" +
	"\bcache_kb\x18\x04 \x01(\x05R\acacheKb\"\xa6\x01\n" +
	"\n" +
	"CpuPackage\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1c\n" +
	"\tmicrocode\x18\x03 \x01(\tR\tmicrocode\x12\x14\n" +
	"\x05flags\x18\x04 \x03(\tR\x05flags\x12-\n" +
	"\x05cores\x18\x05 \x03(\v2\x17.fstmon.dto.CpuCoreInfoR\x05cores\"B\n" +
	"\x0eCpuCoreMetrics\x12\x12\n" +
	"\x04load\x18\x01 \x01(\x01R\x04load\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x01R\tfrequency\"t\n" +
	"\n" +
	"CpuMetrics\x124\n" +
	"\aaverage\x18\x01 \x01(\v2\x1a.fstmon.dto.CpuCoreMetricsR\aaverage\x120\n" +
	"\x05cores\x18\x02 \x03(\v2\x1a.fstmon.dto.CpuCoreMetricsR\x05cores\"\x13\n" +
	"\x11GetCpuInfoRequest\"\x16\n" +
	"\x14GetCpuMetricsRequest\">\n" +
	"\x12CpuPackageResponse\x12(\n" +
	"\x03cpu\x18\x01 \x01(\v2\x16.fstmon.dto.CpuPackageR\x03cpu\"F\n" +
	"\x12CpuMetricsResponse\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x16.fstmon.dto.CpuMetricsR\ametrics\"\x81\x03\n" +
	"\vInterfaceIO\x125\n" +
	"\vbytes_total\x18\x01 \x01(\v2\x14.fstmon.dto.IOUint64R\n" +
	"bytesTotal\x129\n" +
	"\rpackets_total\x18\x02 \x01(\v2\x14.fstmon.dto.IOUint64R\fpacketsTotal\x12D\n" +
	"\x13error_packets_total\x18\x03 \x01(\v2\x14.fstmon.dto.IOUint64R\x11errorPacketsTotal\x12B\n" +
	"\x12drop_packets_total\x18\x04 \x01(\v2\x14.fstmon.dto.IOUint64R\x10dropPacketsTotal\x128\n" +
	"\rbytes_per_sec\x18\x05 \x01(\v2\x14.fstmon.dto.IOUint64R\vbytesPerSec\x12<\n" +
	"\x0fpackets_per_sec\x18\x06 \x01(\v2\x14.fstmon.dto.IOUint64R\rpacketsPerSec\"\xb0\x01\n" +
	"\fInterfacesIO\x12H\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2(.fstmon.dto.InterfacesIO.InterfacesEntryR\n" +
	"interfaces\x1aV\n" +
	"\x0fInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.fstmon.dto.InterfaceIOR\x05value:\x028\x01\"\x18\n" +
	"\x16GetInterfacesIORequest\"D\n" +
	"\x14InterfacesIOResponse\x12,\n" +
	"\x04data\x18\x01 \x01(\v2\x18.fstmon.dto.InterfacesIOR\x04data\"\xf8\x01\n" +
	"\n" +
	"SystemInfo\x121\n" +
	"\x06uptime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12-\n" +
	"\x04idle\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x04idle\x12\x14\n" +
	"\x05load1\x18\x03 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x04 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x05 \x01(\x01R\x06load15\x12#\n" +
	"\rrunning_procs\x18\x06 \x01(\x05R\frunningProcs\x12\x1f\n" +
	"\vtotal_procs\x18\a \x01(\x05R\n" +
	"totalProcs\"\x16\n" +
	"\x14GetSystemInfoRequest\"D\n" +
	"\x12SystemInfoResponse\x12.\n" +
	"\x06system\x18\x01 \x01(\v2\x16.fstmon.dto.SystemInfoR\x06system\"\xba\x02\n" +
	"\rMemoryMetrics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x04 \x01(\x04R\x04free\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x05 \x01(\x04R\tswapTotal\x12%\n" +
	"\x0eswap_available\x18\x06 \x01(\x04R\rswapAvailable\x12\x1b\n" +
	"\tswap_used\x18\a \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\b \x01(\x04R\bswapFree\x12!\n" +
	"\fused_percent\x18\t \x01(\x01R\vusedPercent\x12*\n" +
	"\x11swap_used_percent\x18\n" +
	" \x01(\x01R\x0fswapUsedPercent\"\x19\n" +
	"\x17GetMemoryMetricsRequest\"J\n" +
	"\x15MemoryMetricsResponse\x121\n" +
	"\x06memory\x18\x01 \x01(\v2\x19.fstmon.dto.MemoryMetricsR\x06memory\"P\n" +
	"\x0eThermalMetrics\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x01R\acurrent\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x12\x12\n" +
	"\x04crit\x18\x03 \x01(\x01R\x04crit\"\xb1\x01\n" +
	"\x11ThermalMetricsMap\x12D\n" +
	"\asensors\x18\x01 \x03(\v2*.fstmon.dto.ThermalMetricsMap.SensorsEntryR\asensors\x1aV\n" +
	"\fSensorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.fstmon.dto.ThermalMetricsR\x05value:\x028\x01\"\x13\n" +
	"\x11GetThermalRequest\"J\n" +
	"\x0fThermalResponse\x127\n" +
	"\ametrics\x18\x01 \x01(\v2\x1d.fstmon.dto.ThermalMetricsMapR\ametrics\"\x86\x02\n" +
	"\x0ePartitionUsage\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\x12!\n" +
	"\finodes_total\x18\x05 \x01(\x04R\vinodesTotal\x12\x1f\n" +
	"\vinodes_used\x18\x06 \x01(\x04R\n" +
	"inodesUsed\x12\x1f\n" +
	"\vinodes_free\x18\a \x01(\x04R\n" +
	"inodesFree\x12.\n" +
	"\x13inodes_used_percent\x18\b \x01(\x01R\x11inodesUsedPercent\"\xa5\x01\n" +
	"\tPartition\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05mount\x18\x02 \x01(\tR\x05mount\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x03 \x01(\tR\n" +
	"filesystem\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x120\n" +
	"\x05usage\x18\x05 \x01(\v2\x1a.fstmon.dto.PartitionUsageR\x05usage\"C\n" +
	"\n" +
	"Partitions\x125\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x15.fstmon.dto.PartitionR\n" +
	"partitions\"\x8a\x04\n" +
	"\x06DiskIO\x12(\n" +
	"\x10iops_in_progress\x18\x01 \x01(\x04R\x0eiopsInProgress\x12&\n" +
	"\x03ops\x18\x02 \x01(\v2\x14.fstmon.dto.IOUint64R\x03ops\x123\n" +
	"\n" +
	"merged_ops\x18\x03 \x01(\v2\x14.fstmon.dto.IOUint64R\tmergedOps\x12*\n" +
	"\x05bytes\x18\x04 \x01(\v2\x14.fstmon.dto.IOUint64R\x05bytes\x124\n" +
	"\vops_per_sec\x18\x05 \x01(\v2\x14.fstmon.dto.IOUint64R\topsPerSec\x12A\n" +
	"\x12merged_ops_per_sec\x18\x06 \x01(\v2\x14.fstmon.dto.IOUint64R\x0fmergedOpsPerSec\x128\n" +
	"\rbytes_per_sec\x18\a \x01(\v2\x14.fstmon.dto.IOUint64R\vbytesPerSec\x12*\n" +
	"\x04time\x18\b \x01(\v2\x16.fstmon.dto.IODurationR\x04time\x122\n" +
	"\aio_time\x18\t \x01(\v2\x19.google.protobuf.DurationR\x06ioTime\x12:\n" +
	"\vweighted_io\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\n" +
	"weightedIo\"\x91\x01\n" +
	"\tDiskIOMap\x126\n" +
	"\x05disks\x18\x01 \x03(\v2 .fstmon.dto.DiskIOMap.DisksEntryR\x05disks\x1aL\n" +
	"\n" +
	"DisksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.fstmon.dto.DiskIOR\x05value:\x028\x01\"\x16\n" +
	"\x14GetPartitionsRequest\"\x12\n" +
	"\x10GetDiskIORequest\"L\n" +
	"\x12PartitionsResponse\x126\n" +
	"\n" +
	"partitions\x18\x01 \x01(\v2\x16.fstmon.dto.PartitionsR\n" +
	"partitions\":\n" +
	"\x11DiskIOMapResponse\x12%\n" +
	"\x02io\x18\x01 \x01(\v2\x15.fstmon.dto.DiskIOMapR\x02ioB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_dto_proto_rawDescOnce sync.Once
	file_dto_proto_rawDescData []byte
)

func file_dto_proto_rawDescGZIP() []byte {
	file_dto_proto_rawDescOnce.Do(func() {
		file_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dto_proto_rawDesc), len(file_dto_proto_rawDesc)))
	})
	return file_dto_proto_rawDescData
}

var file_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_dto_proto_goTypes = []any{
	(*IOUint64)(nil),                // 0: fstmon.dto.IOUint64
	(*IOFloat64)(nil),               // 1: fstmon.dto.IOFloat64
	(*IODuration)(nil),              // 2: fstmon.dto.IODuration
	(*CpuCoreInfo)(nil),             // 3: fstmon.dto.CpuCoreInfo
	(*CpuPackage)(nil),              // 4: fstmon.dto.CpuPackage
	(*CpuCoreMetrics)(nil),          // 5: fstmon.dto.CpuCoreMetrics
	(*CpuMetrics)(nil),              // 6: fstmon.dto.CpuMetrics
	(*GetCpuInfoRequest)(nil),       // 7: fstmon.dto.GetCpuInfoRequest
	(*GetCpuMetricsRequest)(nil),    // 8: fstmon.dto.GetCpuMetricsRequest
	(*CpuPackageResponse)(nil),      // 9: fstmon.dto.CpuPackageResponse
	(*CpuMetricsResponse)(nil),      // 10: fstmon.dto.CpuMetricsResponse
	(*InterfaceIO)(nil),             // 11: fstmon.dto.InterfaceIO
	(*InterfacesIO)(nil),            // 12: fstmon.dto.InterfacesIO
	(*GetInterfacesIORequest)(nil),  // 13: fstmon.dto.GetInterfacesIORequest
	(*InterfacesIOResponse)(nil),    // 14: fstmon.dto.InterfacesIOResponse
	(*SystemInfo)(nil),              // 15: fstmon.dto.SystemInfo
	(*GetSystemInfoRequest)(nil),    // 16: fstmon.dto.GetSystemInfoRequest
	(*SystemInfoResponse)(nil),      // 17: fstmon.dto.SystemInfoResponse
	(*MemoryMetrics)(nil),           // 18: fstmon.dto.MemoryMetrics
	(*GetMemoryMetricsRequest)(nil), // 19: fstmon.dto.GetMemoryMetricsRequest
	(*MemoryMetricsResponse)(nil),   // 20: fstmon.dto.MemoryMetricsResponse
	(*ThermalMetrics)(nil),          // 21: fstmon.dto.ThermalMetrics
	(*ThermalMetricsMap)(nil),       // 22: fstmon.dto.ThermalMetricsMap
	(*GetThermalRequest)(nil),       // 23: fstmon.dto.GetThermalRequest
	(*ThermalResponse)(nil),         // 24: fstmon.dto.ThermalResponse
	(*PartitionUsage)(nil),          // 25: fstmon.dto.PartitionUsage
	(*Partition)(nil),               // 26: fstmon.dto.Partition
	(*Partitions)(nil),              // 27: fstmon.dto.Partitions
	(*DiskIO)(nil),                  // 28: fstmon.dto.DiskIO
	(*DiskIOMap)(nil),               // 29: fstmon.dto.DiskIOMap
	(*GetPartitionsRequest)(nil),    // 30: fstmon.dto.GetPartitionsRequest
	(*GetDiskIORequest)(nil),        // 31: fstmon.dto.GetDiskIORequest
	(*PartitionsResponse)(nil),      // 32: fstmon.dto.PartitionsResponse
	(*DiskIOMapResponse)(nil),       // 33: fstmon.dto.DiskIOMapResponse
	nil,                             // 34: fstmon.dto.InterfacesIO.InterfacesEntry
	nil,                             // 35: fstmon.dto.ThermalMetricsMap.SensorsEntry
	nil,                             // 36: fstmon.dto.DiskIOMap.DisksEntry
	(*durationpb.Duration)(nil),     // 37: google.protobuf.Duration
}
var file_dto_proto_depIdxs = []int32{
	37, // 0: fstmon.dto.IODuration.summary:type_name -> google.protobuf.Duration
	37, // 1: fstmon.dto.IODuration.rx:type_name -> google.protobuf.Duration
	37, // 2: fstmon.dto.IODuration.tx:type_name -> google.protobuf.Duration
	3,  // 3: fstmon.dto.CpuPackage.cores:type_name -> fstmon.dto.CpuCoreInfo
	5,  // 4: fstmon.dto.CpuMetrics.average:type_name -> fstmon.dto.CpuCoreMetrics
	5,  // 5: fstmon.dto.CpuMetrics.cores:type_name -> fstmon.dto.CpuCoreMetrics
	4,  // 6: fstmon.dto.CpuPackageResponse.cpu:type_name -> fstmon.dto.CpuPackage
	6,  // 7: fstmon.dto.CpuMetricsResponse.metrics:type_name -> fstmon.dto.CpuMetrics
	0,  // 8: fstmon.dto.InterfaceIO.bytes_total:type_name -> fstmon.dto.IOUint64
	0,  // 9: fstmon.dto.InterfaceIO.packets_total:type_name -> fstmon.dto.IOUint64
	0,  // 10: fstmon.dto.InterfaceIO.error_packets_total:type_name -> fstmon.dto.IOUint64
	0,  // 11: fstmon.dto.InterfaceIO.drop_packets_total:type_name -> fstmon.dto.IOUint64
	0,  // 12: fstmon.dto.InterfaceIO.bytes_per_sec:type_name -> fstmon.dto.IOUint64
	0,  // 13: fstmon.dto.InterfaceIO.packets_per_sec:type_name -> fstmon.dto.IOUint64
	34, // 14: fstmon.dto.InterfacesIO.interfaces:type_name -> fstmon.dto.InterfacesIO.InterfacesEntry
	12, // 15: fstmon.dto.InterfacesIOResponse.data:type_name -> fstmon.dto.InterfacesIO
	37, // 16: fstmon.dto.SystemInfo.uptime:type_name -> google.protobuf.Duration
	37, // 17: fstmon.dto.SystemInfo.idle:type_name -> google.protobuf.Duration
	15, // 18: fstmon.dto.SystemInfoResponse.system:type_name -> fstmon.dto.SystemInfo
	18, // 19: fstmon.dto.MemoryMetricsResponse.memory:type_name -> fstmon.dto.MemoryMetrics
	35, // 20: fstmon.dto.ThermalMetricsMap.sensors:type_name -> fstmon.dto.ThermalMetricsMap.SensorsEntry
	22, // 21: fstmon.dto.ThermalResponse.metrics:type_name -> fstmon.dto.ThermalMetricsMap
	25, // 22: fstmon.dto.Partition.usage:type_name -> fstmon.dto.PartitionUsage
	26, // 23: fstmon.dto.Partitions.partitions:type_name -> fstmon.dto.Partition
	0,  // 24: fstmon.dto.DiskIO.ops:type_name -> fstmon.dto.IOUint64
	0,  // 25: fstmon.dto.DiskIO.merged_ops:type_name -> fstmon.dto.IOUint64
	0,  // 26: fstmon.dto.DiskIO.bytes:type_name -> fstmon.dto.IOUint64
	0,  // 27: fstmon.dto.DiskIO.ops_per_sec:type_name -> fstmon.dto.IOUint64
	0,  // 28: fstmon.dto.DiskIO.merged_ops_per_sec:type_name -> fstmon.dto.IOUint64
	0,  // 29: fstmon.dto.DiskIO.bytes_per_sec:type_name -> fstmon.dto.IOUint64
	2,  // 30: fstmon.dto.DiskIO.time:type_name -> fstmon.dto.IODuration
	37, // 31: fstmon.dto.DiskIO.io_time:type_name -> google.protobuf.Duration
	37, // 32: fstmon.dto.DiskIO.weighted_io:type_name -> google.protobuf.Duration
	36, // 33: fstmon.dto.DiskIOMap.disks:type_name -> fstmon.dto.DiskIOMap.DisksEntry
	27, // 34: fstmon.dto.PartitionsResponse.partitions:type_name -> fstmon.dto.Partitions
	29, // 35: fstmon.dto.DiskIOMapResponse.io:type_name -> fstmon.dto.DiskIOMap
	11, // 36: fstmon.dto.InterfacesIO.InterfacesEntry.value:type_name -> fstmon.dto.InterfaceIO
	21, // 37: fstmon.dto.ThermalMetricsMap.SensorsEntry.value:type_name -> fstmon.dto.ThermalMetrics
	28, // 38: fstmon.dto.DiskIOMap.DisksEntry.value:type_name -> fstmon.dto.DiskIO
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_dto_proto_init() }
func file_dto_proto_init() {
	if File_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dto_proto_rawDesc), len(file_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dto_proto_goTypes,
		DependencyIndexes: file_dto_proto_depIdxs,
		MessageInfos:      file_dto_proto_msgTypes,
	}.Build()
	File_dto_proto = out.File
	file_dto_proto_goTypes = nil
	file_dto_proto_depIdxs = nil
}
