// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: memory.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Total           uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available       uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Used            uint64                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Free            uint64                 `protobuf:"varint,4,opt,name=free,proto3" json:"free,omitempty"`
	SwapTotal       uint64                 `protobuf:"varint,5,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapAvailable   uint64                 `protobuf:"varint,6,opt,name=swap_available,json=swapAvailable,proto3" json:"swap_available,omitempty"`
	SwapUsed        uint64                 `protobuf:"varint,7,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree        uint64                 `protobuf:"varint,8,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	UsedPercent     float64                `protobuf:"fixed64,9,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	SwapUsedPercent float64                `protobuf:"fixed64,10,opt,name=swap_used_percent,json=swapUsedPercent,proto3" json:"swap_used_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemoryMetrics) GetSwapAvailable() uint64 {
	if x != nil {
		return x.SwapAvailable
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MemoryMetrics) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *MemoryMetrics) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsedPercent() float64 {
	if x != nil {
		return x.SwapUsedPercent
	}
	return 0
}

type GetMemoryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryMetricsRequest) Reset() {
	*x = GetMemoryMetricsRequest{}
	mi := &file_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryMetricsRequest) ProtoMessage() {}

func (x *GetMemoryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

type MemoryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryMetrics         `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetricsResponse) Reset() {
	*x = MemoryMetricsResponse{}
	mi := &file_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetricsResponse) ProtoMessage() {}

func (x *MemoryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetricsResponse.ProtoReflect.Descriptor instead.
func (*MemoryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryMetricsResponse) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_memory_proto protoreflect.FileDescriptor

const file_memory_proto_rawDesc = "" +
	"\n" +
	"\fmemory.proto\x12\rfstmon.memory\"\xba\x02\n" +
	"\rMemoryMetrics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x04 \x01(\x04R\x04free\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x05 \x01(\x04R\tswapTotal\x12%\n" +
	"\x0eswap_available\x18\x06 \x01(\x04R\rswapAvailable\x12\x1b\n" +
	"\tswap_used\x18\a \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\b \x01(\x04R\bswapFree\x12!\n" +
	"\fused_percent\x18\t \x01(\x01R\vusedPercent\x12*\n" +
	"\x11swap_used_percent\x18\n" +
	" \x01(\x01R\x0fswapUsedPercent\"\x19\n" +
	"\x17GetMemoryMetricsRequest\"M\n" +
	"\x15MemoryMetricsResponse\x124\n" +
	"\x06memory\x18\x01 \x01(\v2\x1c.fstmon.memory.MemoryMetricsR\x06memory2q\n" +
	"\rMemoryService\x12`\n" +
	"\x10GetMemoryMetrics\x12&.fstmon.memory.GetMemoryMetricsRequest\x1a$.fstmon.memory.MemoryMetricsResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_memory_proto_rawDescOnce sync.Once
	file_memory_proto_rawDescData []byte
)

func file_memory_proto_rawDescGZIP() []byte {
	file_memory_proto_rawDescOnce.Do(func() {
		file_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)))
	})
	return file_memory_proto_rawDescData
}

var file_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_memory_proto_goTypes = []any{
	(*MemoryMetrics)(nil),           // 0: fstmon.memory.MemoryMetrics
	(*GetMemoryMetricsRequest)(nil), // 1: fstmon.memory.GetMemoryMetricsRequest
	(*MemoryMetricsResponse)(nil),   // 2: fstmon.memory.MemoryMetricsResponse
}
var file_memory_proto_depIdxs = []int32{
	0, // 0: fstmon.memory.MemoryMetricsResponse.memory:type_name -> fstmon.memory.MemoryMetrics
	1, // 1: fstmon.memory.MemoryService.GetMemoryMetrics:input_type -> fstmon.memory.GetMemoryMetricsRequest
	2, // 2: fstmon.memory.MemoryService.GetMemoryMetrics:output_type -> fstmon.memory.MemoryMetricsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_memory_proto_init() }
func file_memory_proto_init() {
	if File_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_proto_goTypes,
		DependencyIndexes: file_memory_proto_depIdxs,
		MessageInfos:      file_memory_proto_msgTypes,
	}.Build()
	File_memory_proto = out.File
	file_memory_proto_goTypes = nil
	file_memory_proto_depIdxs = nil
}
