// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: network.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metrics of a network interface
type InterfaceIO struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BytesTotal        *IOUint64              `protobuf:"bytes,1,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	PacketsTotal      *IOUint64              `protobuf:"bytes,2,opt,name=packets_total,json=packetsTotal,proto3" json:"packets_total,omitempty"`
	ErrorPacketsTotal *IOUint64              `protobuf:"bytes,3,opt,name=error_packets_total,json=errorPacketsTotal,proto3" json:"error_packets_total,omitempty"`
	DropPacketsTotal  *IOUint64              `protobuf:"bytes,4,opt,name=drop_packets_total,json=dropPacketsTotal,proto3" json:"drop_packets_total,omitempty"`
	BytesPerSec       *IOUint64              `protobuf:"bytes,5,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	PacketsPerSec     *IOUint64              `protobuf:"bytes,6,opt,name=packets_per_sec,json=packetsPerSec,proto3" json:"packets_per_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InterfaceIO) Reset() {
	*x = InterfaceIO{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceIO) ProtoMessage() {}

func (x *InterfaceIO) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceIO.ProtoReflect.Descriptor instead.
func (*InterfaceIO) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *InterfaceIO) GetBytesTotal() *IOUint64 {
	if x != nil {
		return x.BytesTotal
	}
	return nil
}

func (x *InterfaceIO) GetPacketsTotal() *IOUint64 {
	if x != nil {
		return x.PacketsTotal
	}
	return nil
}

func (x *InterfaceIO) GetErrorPacketsTotal() *IOUint64 {
	if x != nil {
		return x.ErrorPacketsTotal
	}
	return nil
}

func (x *InterfaceIO) GetDropPacketsTotal() *IOUint64 {
	if x != nil {
		return x.DropPacketsTotal
	}
	return nil
}

func (x *InterfaceIO) GetBytesPerSec() *IOUint64 {
	if x != nil {
		return x.BytesPerSec
	}
	return nil
}

func (x *InterfaceIO) GetPacketsPerSec() *IOUint64 {
	if x != nil {
		return x.PacketsPerSec
	}
	return nil
}

type InterfacesIO struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Interfaces    map[string]*InterfaceIO `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesIO) Reset() {
	*x = InterfacesIO{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesIO) ProtoMessage() {}

func (x *InterfacesIO) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesIO.ProtoReflect.Descriptor instead.
func (*InterfacesIO) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *InterfacesIO) GetInterfaces() map[string]*InterfaceIO {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type GetInterfacesIORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfacesIORequest) Reset() {
	*x = GetInterfacesIORequest{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfacesIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfacesIORequest) ProtoMessage() {}

func (x *GetInterfacesIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfacesIORequest.ProtoReflect.Descriptor instead.
func (*GetInterfacesIORequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

type InterfacesIOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *InterfacesIO          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesIOResponse) Reset() {
	*x = InterfacesIOResponse{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesIOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesIOResponse) ProtoMessage() {}

func (x *InterfacesIOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesIOResponse.ProtoReflect.Descriptor instead.
func (*InterfacesIOResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *InterfacesIOResponse) GetData() *InterfacesIO {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\x0efstmon.network\x1a\fcommon.proto\"\x93\x03\n" +
	"\vInterfaceIO\x128\n" +
	"\vbytes_total\x18\x01 \x01(\v2\x17.fstmon.common.IOUint64R\n" +
	"bytesTotal\x12<\n" +
	"\rpackets_total\x18\x02 \x01(\v2\x17.fstmon.common.IOUint64R\fpacketsTotal\x12G\n" +
	"\x13error_packets_total\x18\x03 \x01(\v2\x17.fstmon.common.IOUint64R\x11errorPacketsTotal\x12E\n" +
	"\x12drop_packets_total\x18\x04 \x01(\v2\x17.fstmon.common.IOUint64R\x10dropPacketsTotal\x12;\n" +
	"\rbytes_per_sec\x18\x05 \x01(\v2\x17.fstmon.common.IOUint64R\vbytesPerSec\x12?\n" +
	"\x0fpackets_per_sec\x18\x06 \x01(\v2\x17.fstmon.common.IOUint64R\rpacketsPerSec\"\xb8\x01\n" +
	"\fInterfacesIO\x12L\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2,.fstmon.network.InterfacesIO.InterfacesEntryR\n" +
	"interfaces\x1aZ\n" +
	"\x0fInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.fstmon.network.InterfaceIOR\x05value:\x028\x01\"\x18\n" +
	"\x16GetInterfacesIORequest\"H\n" +
	"\x14InterfacesIOResponse\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.fstmon.network.InterfacesIOR\x04data2q\n" +
	"\x0eNetworkService\x12_\n" +
	"\x0fGetInterfacesIO\x12&.fstmon.network.GetInterfacesIORequest\x1a$.fstmon.network.InterfacesIOResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_network_proto_goTypes = []any{
	(*InterfaceIO)(nil),            // 0: fstmon.network.InterfaceIO
	(*InterfacesIO)(nil),           // 1: fstmon.network.InterfacesIO
	(*GetInterfacesIORequest)(nil), // 2: fstmon.network.GetInterfacesIORequest
	(*InterfacesIOResponse)(nil),   // 3: fstmon.network.InterfacesIOResponse
	nil,                            // 4: fstmon.network.InterfacesIO.InterfacesEntry
	(*IOUint64)(nil),               // 5: fstmon.common.IOUint64
}
var file_network_proto_depIdxs = []int32{
	5,  // 0: fstmon.network.InterfaceIO.bytes_total:type_name -> fstmon.common.IOUint64
	5,  // 1: fstmon.network.InterfaceIO.packets_total:type_name -> fstmon.common.IOUint64
	5,  // 2: fstmon.network.InterfaceIO.error_packets_total:type_name -> fstmon.common.IOUint64
	5,  // 3: fstmon.network.InterfaceIO.drop_packets_total:type_name -> fstmon.common.IOUint64
	5,  // 4: fstmon.network.InterfaceIO.bytes_per_sec:type_name -> fstmon.common.IOUint64
	5,  // 5: fstmon.network.InterfaceIO.packets_per_sec:type_name -> fstmon.common.IOUint64
	4,  // 6: fstmon.network.InterfacesIO.interfaces:type_name -> fstmon.network.InterfacesIO.InterfacesEntry
	1,  // 7: fstmon.network.InterfacesIOResponse.data:type_name -> fstmon.network.InterfacesIO
	0,  // 8: fstmon.network.InterfacesIO.InterfacesEntry.value:type_name -> fstmon.network.InterfaceIO
	2,  // 9: fstmon.network.NetworkService.GetInterfacesIO:input_type -> fstmon.network.GetInterfacesIORequest
	3,  // 10: fstmon.network.NetworkService.GetInterfacesIO:output_type -> fstmon.network.InterfacesIOResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
