// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: storage.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Partition usage (dynamic)
type PartitionUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Total             uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Used              uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	Free              uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent       float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	InodesTotal       uint64                 `protobuf:"varint,5,opt,name=inodes_total,json=inodesTotal,proto3" json:"inodes_total,omitempty"`
	InodesUsed        uint64                 `protobuf:"varint,6,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	InodesFree        uint64                 `protobuf:"varint,7,opt,name=inodes_free,json=inodesFree,proto3" json:"inodes_free,omitempty"`
	InodesUsedPercent float64                `protobuf:"fixed64,8,opt,name=inodes_used_percent,json=inodesUsedPercent,proto3" json:"inodes_used_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PartitionUsage) Reset() {
	*x = PartitionUsage{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionUsage) ProtoMessage() {}

func (x *PartitionUsage) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionUsage.ProtoReflect.Descriptor instead.
func (*PartitionUsage) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *PartitionUsage) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PartitionUsage) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *PartitionUsage) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *PartitionUsage) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *PartitionUsage) GetInodesTotal() uint64 {
	if x != nil {
		return x.InodesTotal
	}
	return 0
}

func (x *PartitionUsage) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *PartitionUsage) GetInodesFree() uint64 {
	if x != nil {
		return x.InodesFree
	}
	return 0
}

func (x *PartitionUsage) GetInodesUsedPercent() float64 {
	if x != nil {
		return x.InodesUsedPercent
	}
	return 0
}

// Partition (static)
type Partition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Mount         string                 `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
	Filesystem    string                 `protobuf:"bytes,3,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Usage         *PartitionUsage        `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Partition) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Partition) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Partition) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Partition) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Partition) GetUsage() *PartitionUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Partitions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*Partition           `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partitions) Reset() {
	*x = Partitions{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partitions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partitions) ProtoMessage() {}

func (x *Partitions) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partitions.ProtoReflect.Descriptor instead.
func (*Partitions) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Partitions) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

// Disk I/O
type DiskIO struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IopsInProgress  uint64                 `protobuf:"varint,1,opt,name=iops_in_progress,json=iopsInProgress,proto3" json:"iops_in_progress,omitempty"`
	Ops             *IOUint64              `protobuf:"bytes,2,opt,name=ops,proto3" json:"ops,omitempty"`
	MergedOps       *IOUint64              `protobuf:"bytes,3,opt,name=merged_ops,json=mergedOps,proto3" json:"merged_ops,omitempty"`
	Bytes           *IOUint64              `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	OpsPerSec       *IOUint64              `protobuf:"bytes,5,opt,name=ops_per_sec,json=opsPerSec,proto3" json:"ops_per_sec,omitempty"`
	MergedOpsPerSec *IOUint64              `protobuf:"bytes,6,opt,name=merged_ops_per_sec,json=mergedOpsPerSec,proto3" json:"merged_ops_per_sec,omitempty"`
	BytesPerSec     *IOUint64              `protobuf:"bytes,7,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	Time            *IODuration            `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	IoTime          *durationpb.Duration   `protobuf:"bytes,9,opt,name=io_time,json=ioTime,proto3" json:"io_time,omitempty"`
	WeightedIo      *durationpb.Duration   `protobuf:"bytes,10,opt,name=weighted_io,json=weightedIo,proto3" json:"weighted_io,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiskIO) Reset() {
	*x = DiskIO{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIO) ProtoMessage() {}

func (x *DiskIO) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIO.ProtoReflect.Descriptor instead.
func (*DiskIO) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *DiskIO) GetIopsInProgress() uint64 {
	if x != nil {
		return x.IopsInProgress
	}
	return 0
}

func (x *DiskIO) GetOps() *IOUint64 {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *DiskIO) GetMergedOps() *IOUint64 {
	if x != nil {
		return x.MergedOps
	}
	return nil
}

func (x *DiskIO) GetBytes() *IOUint64 {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *DiskIO) GetOpsPerSec() *IOUint64 {
	if x != nil {
		return x.OpsPerSec
	}
	return nil
}

func (x *DiskIO) GetMergedOpsPerSec() *IOUint64 {
	if x != nil {
		return x.MergedOpsPerSec
	}
	return nil
}

func (x *DiskIO) GetBytesPerSec() *IOUint64 {
	if x != nil {
		return x.BytesPerSec
	}
	return nil
}

func (x *DiskIO) GetTime() *IODuration {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DiskIO) GetIoTime() *durationpb.Duration {
	if x != nil {
		return x.IoTime
	}
	return nil
}

func (x *DiskIO) GetWeightedIo() *durationpb.Duration {
	if x != nil {
		return x.WeightedIo
	}
	return nil
}

type DiskIOMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         map[string]*DiskIO     `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIOMap) Reset() {
	*x = DiskIOMap{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIOMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIOMap) ProtoMessage() {}

func (x *DiskIOMap) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIOMap.ProtoReflect.Descriptor instead.
func (*DiskIOMap) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *DiskIOMap) GetDisks() map[string]*DiskIO {
	if x != nil {
		return x.Disks
	}
	return nil
}

type GetPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartitionsRequest) Reset() {
	*x = GetPartitionsRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartitionsRequest) ProtoMessage() {}

func (x *GetPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartitionsRequest.ProtoReflect.Descriptor instead.
func (*GetPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

type GetDiskIORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskIORequest) Reset() {
	*x = GetDiskIORequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskIORequest) ProtoMessage() {}

func (x *GetDiskIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskIORequest.ProtoReflect.Descriptor instead.
func (*GetDiskIORequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

type PartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    *Partitions            `protobuf:"bytes,1,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionsResponse) Reset() {
	*x = PartitionsResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionsResponse) ProtoMessage() {}

func (x *PartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionsResponse.ProtoReflect.Descriptor instead.
func (*PartitionsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *PartitionsResponse) GetPartitions() *Partitions {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type DiskIOMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Io            *DiskIOMap             `protobuf:"bytes,1,opt,name=io,proto3" json:"io,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIOMapResponse) Reset() {
	*x = DiskIOMapResponse{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIOMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIOMapResponse) ProtoMessage() {}

func (x *DiskIOMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIOMapResponse.ProtoReflect.Descriptor instead.
func (*DiskIOMapResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *DiskIOMapResponse) GetIo() *DiskIOMap {
	if x != nil {
		return x.Io
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x0efstmon.storage\x1a\x1egoogle/protobuf/duration.proto\x1a\fcommon.proto\"\x86\x02\n" +
	"\x0ePartitionUsage\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\x12!\n" +
	"\finodes_total\x18\x05 \x01(\x04R\vinodesTotal\x12\x1f\n" +
	"\vinodes_used\x18\x06 \x01(\x04R\n" +
	"inodesUsed\x12\x1f\n" +
	"\vinodes_free\x18\a \x01(\x04R\n" +
	"inodesFree\x12.\n" +
	"\x13inodes_used_percent\x18\b \x01(\x01R\x11inodesUsedPercent\"\xa9\x01\n" +
	"\tPartition\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05mount\x18\x02 \x01(\tR\x05mount\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x03 \x01(\tR\n" +
	"filesystem\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x124\n" +
	"\x05usage\x18\x05 \x01(\v2\x1e.fstmon.storage.PartitionUsageR\x05usage\"G\n" +
	"\n" +
	"Partitions\x129\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x19.fstmon.storage.PartitionR\n" +
	"partitions\"\x9f\x04\n" +
	"\x06DiskIO\x12(\n" +
	"\x10iops_in_progress\x18\x01 \x01(\x04R\x0eiopsInProgress\x12)\n" +
	"\x03ops\x18\x02 \x01(\v2\x17.fstmon.common.IOUint64R\x03ops\x126\n" +
	"\n" +
	"merged_ops\x18\x03 \x01(\v2\x17.fstmon.common.IOUint64R\tmergedOps\x12-\n" +
	"\x05bytes\x18\x04 \x01(\v2\x17.fstmon.common.IOUint64R\x05bytes\x127\n" +
	"\vops_per_sec\x18\x05 \x01(\v2\x17.fstmon.common.IOUint64R\topsPerSec\x12D\n" +
	"\x12merged_ops_per_sec\x18\x06 \x01(\v2\x17.fstmon.common.IOUint64R\x0fmergedOpsPerSec\x12;\n" +
	"\rbytes_per_sec\x18\a \x01(\v2\x17.fstmon.common.IOUint64R\vbytesPerSec\x12-\n" +
	"\x04time\x18\b \x01(\v2\x19.fstmon.common.IODurationR\x04time\x122\n" +
	"\aio_time\x18\t \x01(\v2\x19.google.protobuf.DurationR\x06ioTime\x12:\n" +
	"\vweighted_io\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\n" +
	"weightedIo\"\x99\x01\n" +
	"\tDiskIOMap\x12:\n" +
	"\x05disks\x18\x01 \x03(\v2$.fstmon.storage.DiskIOMap.DisksEntryR\x05disks\x1aP\n" +
	"\n" +
	"DisksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.fstmon.storage.DiskIOR\x05value:\x028\x01\"\x16\n" +
	"\x14GetPartitionsRequest\"\x12\n" +
	"\x10GetDiskIORequest\"P\n" +
	"\x12PartitionsResponse\x12:\n" +
	"\n" +
	"partitions\x18\x01 \x01(\v2\x1a.fstmon.storage.PartitionsR\n" +
	"partitions\">\n" +
	"\x11DiskIOMapResponse\x12)\n" +
	"\x02io\x18\x01 \x01(\v2\x19.fstmon.storage.DiskIOMapR\x02io2\xbd\x01\n" +
	"\x0eStorageService\x12Y\n" +
	"\rGetPartitions\x12$.fstmon.storage.GetPartitionsRequest\x1a\".fstmon.storage.PartitionsResponse\x12P\n" +
	"\tGetDiskIO\x12 .fstmon.storage.GetDiskIORequest\x1a!.fstmon.storage.DiskIOMapResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_storage_proto_goTypes = []any{
	(*PartitionUsage)(nil),       // 0: fstmon.storage.PartitionUsage
	(*Partition)(nil),            // 1: fstmon.storage.Partition
	(*Partitions)(nil),           // 2: fstmon.storage.Partitions
	(*DiskIO)(nil),               // 3: fstmon.storage.DiskIO
	(*DiskIOMap)(nil),            // 4: fstmon.storage.DiskIOMap
	(*GetPartitionsRequest)(nil), // 5: fstmon.storage.GetPartitionsRequest
	(*GetDiskIORequest)(nil),     // 6: fstmon.storage.GetDiskIORequest
	(*PartitionsResponse)(nil),   // 7: fstmon.storage.PartitionsResponse
	(*DiskIOMapResponse)(nil),    // 8: fstmon.storage.DiskIOMapResponse
	nil,                          // 9: fstmon.storage.DiskIOMap.DisksEntry
	(*IOUint64)(nil),             // 10: fstmon.common.IOUint64
	(*IODuration)(nil),           // 11: fstmon.common.IODuration
	(*durationpb.Duration)(nil),  // 12: google.protobuf.Duration
}
var file_storage_proto_depIdxs = []int32{
	0,  // 0: fstmon.storage.Partition.usage:type_name -> fstmon.storage.PartitionUsage
	1,  // 1: fstmon.storage.Partitions.partitions:type_name -> fstmon.storage.Partition
	10, // 2: fstmon.storage.DiskIO.ops:type_name -> fstmon.common.IOUint64
	10, // 3: fstmon.storage.DiskIO.merged_ops:type_name -> fstmon.common.IOUint64
	10, // 4: fstmon.storage.DiskIO.bytes:type_name -> fstmon.common.IOUint64
	10, // 5: fstmon.storage.DiskIO.ops_per_sec:type_name -> fstmon.common.IOUint64
	10, // 6: fstmon.storage.DiskIO.merged_ops_per_sec:type_name -> fstmon.common.IOUint64
	10, // 7: fstmon.storage.DiskIO.bytes_per_sec:type_name -> fstmon.common.IOUint64
	11, // 8: fstmon.storage.DiskIO.time:type_name -> fstmon.common.IODuration
	12, // 9: fstmon.storage.DiskIO.io_time:type_name -> google.protobuf.Duration
	12, // 10: fstmon.storage.DiskIO.weighted_io:type_name -> google.protobuf.Duration
	9,  // 11: fstmon.storage.DiskIOMap.disks:type_name -> fstmon.storage.DiskIOMap.DisksEntry
	2,  // 12: fstmon.storage.PartitionsResponse.partitions:type_name -> fstmon.storage.Partitions
	4,  // 13: fstmon.storage.DiskIOMapResponse.io:type_name -> fstmon.storage.DiskIOMap
	3,  // 14: fstmon.storage.DiskIOMap.DisksEntry.value:type_name -> fstmon.storage.DiskIO
	5,  // 15: fstmon.storage.StorageService.GetPartitions:input_type -> fstmon.storage.GetPartitionsRequest
	6,  // 16: fstmon.storage.StorageService.GetDiskIO:input_type -> fstmon.storage.GetDiskIORequest
	7,  // 17: fstmon.storage.StorageService.GetPartitions:output_type -> fstmon.storage.PartitionsResponse
	8,  // 18: fstmon.storage.StorageService.GetDiskIO:output_type -> fstmon.storage.DiskIOMapResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
