// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: system.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        *durationpb.Duration   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Idle          *durationpb.Duration   `protobuf:"bytes,2,opt,name=idle,proto3" json:"idle,omitempty"`
	Load1         float64                `protobuf:"fixed64,3,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,4,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,5,opt,name=load15,proto3" json:"load15,omitempty"`
	RunningProcs  int32                  `protobuf:"varint,6,opt,name=running_procs,json=runningProcs,proto3" json:"running_procs,omitempty"`
	TotalProcs    int32                  `protobuf:"varint,7,opt,name=total_procs,json=totalProcs,proto3" json:"total_procs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *SystemInfo) GetIdle() *durationpb.Duration {
	if x != nil {
		return x.Idle
	}
	return nil
}

func (x *SystemInfo) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *SystemInfo) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *SystemInfo) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *SystemInfo) GetRunningProcs() int32 {
	if x != nil {
		return x.RunningProcs
	}
	return 0
}

func (x *SystemInfo) GetTotalProcs() int32 {
	if x != nil {
		return x.TotalProcs
	}
	return 0
}

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        *SystemInfo            `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *SystemInfoResponse) GetSystem() *SystemInfo {
	if x != nil {
		return x.System
	}
	return nil
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\rfstmon.system\x1a\x1egoogle/protobuf/duration.proto\"\xf8\x01\n" +
	"\n" +
	"SystemInfo\x121\n" +
	"\x06uptime\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12-\n" +
	"\x04idle\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x04idle\x12\x14\n" +
	"\x05load1\x18\x03 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x04 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\x05 \x01(\x01R\x06load15\x12#\n" +
	"\rrunning_procs\x18\x06 \x01(\x05R\frunningProcs\x12\x1f\n" +
	"\vtotal_procs\x18\a \x01(\x05R\n" +
	"totalProcs\"\x16\n" +
	"\x14GetSystemInfoRequest\"G\n" +
	"\x12SystemInfoResponse\x121\n" +
	"\x06system\x18\x01 \x01(\v2\x19.fstmon.system.SystemInfoR\x06system2h\n" +
	"\rSystemService\x12W\n" +
	"\rGetSystemInfo\x12#.fstmon.system.GetSystemInfoRequest\x1a!.fstmon.system.SystemInfoResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_system_proto_goTypes = []any{
	(*SystemInfo)(nil),           // 0: fstmon.system.SystemInfo
	(*GetSystemInfoRequest)(nil), // 1: fstmon.system.GetSystemInfoRequest
	(*SystemInfoResponse)(nil),   // 2: fstmon.system.SystemInfoResponse
	(*durationpb.Duration)(nil),  // 3: google.protobuf.Duration
}
var file_system_proto_depIdxs = []int32{
	3, // 0: fstmon.system.SystemInfo.uptime:type_name -> google.protobuf.Duration
	3, // 1: fstmon.system.SystemInfo.idle:type_name -> google.protobuf.Duration
	0, // 2: fstmon.system.SystemInfoResponse.system:type_name -> fstmon.system.SystemInfo
	1, // 3: fstmon.system.SystemService.GetSystemInfo:input_type -> fstmon.system.GetSystemInfoRequest
	2, // 4: fstmon.system.SystemService.GetSystemInfo:output_type -> fstmon.system.SystemInfoResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
