// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: thermal.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Thermal metrics
type ThermalMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       float64                `protobuf:"fixed64,1,opt,name=current,proto3" json:"current,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Crit          float64                `protobuf:"fixed64,3,opt,name=crit,proto3" json:"crit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThermalMetrics) Reset() {
	*x = ThermalMetrics{}
	mi := &file_thermal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalMetrics) ProtoMessage() {}

func (x *ThermalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_thermal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalMetrics.ProtoReflect.Descriptor instead.
func (*ThermalMetrics) Descriptor() ([]byte, []int) {
	return file_thermal_proto_rawDescGZIP(), []int{0}
}

func (x *ThermalMetrics) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ThermalMetrics) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ThermalMetrics) GetCrit() float64 {
	if x != nil {
		return x.Crit
	}
	return 0
}

type ThermalMetricsMap struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Sensors       map[string]*ThermalMetrics `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThermalMetricsMap) Reset() {
	*x = ThermalMetricsMap{}
	mi := &file_thermal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalMetricsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalMetricsMap) ProtoMessage() {}

func (x *ThermalMetricsMap) ProtoReflect() protoreflect.Message {
	mi := &file_thermal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalMetricsMap.ProtoReflect.Descriptor instead.
func (*ThermalMetricsMap) Descriptor() ([]byte, []int) {
	return file_thermal_proto_rawDescGZIP(), []int{1}
}

func (x *ThermalMetricsMap) GetSensors() map[string]*ThermalMetrics {
	if x != nil {
		return x.Sensors
	}
	return nil
}

type GetThermalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThermalRequest) Reset() {
	*x = GetThermalRequest{}
	mi := &file_thermal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThermalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThermalRequest) ProtoMessage() {}

func (x *GetThermalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thermal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThermalRequest.ProtoReflect.Descriptor instead.
func (*GetThermalRequest) Descriptor() ([]byte, []int) {
	return file_thermal_proto_rawDescGZIP(), []int{2}
}

type ThermalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *ThermalMetricsMap     `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThermalResponse) Reset() {
	*x = ThermalResponse{}
	mi := &file_thermal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalResponse) ProtoMessage() {}

func (x *ThermalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thermal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalResponse.ProtoReflect.Descriptor instead.
func (*ThermalResponse) Descriptor() ([]byte, []int) {
	return file_thermal_proto_rawDescGZIP(), []int{3}
}

func (x *ThermalResponse) GetMetrics() *ThermalMetricsMap {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_thermal_proto protoreflect.FileDescriptor

const file_thermal_proto_rawDesc = "" +
	"\n" +
	"\rthermal.proto\x12\x0efstmon.thermal\"P\n" +
	"\x0eThermalMetrics\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x01R\acurrent\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x12\x12\n" +
	"\x04crit\x18\x03 \x01(\x01R\x04crit\"\xb9\x01\n" +
	"\x11ThermalMetricsMap\x12H\n" +
	"\asensors\x18\x01 \x03(\v2..fstmon.thermal.ThermalMetricsMap.SensorsEntryR\asensors\x1aZ\n" +
	"\fSensorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.fstmon.thermal.ThermalMetricsR\x05value:\x028\x01\"\x13\n" +
	"\x11GetThermalRequest\"N\n" +
	"\x0fThermalResponse\x12;\n" +
	"\ametrics\x18\x01 \x01(\v2!.fstmon.thermal.ThermalMetricsMapR\ametrics2b\n" +
	"\x0eThermalService\x12P\n" +
	"\n" +
	"GetThermal\x12!.fstmon.thermal.GetThermalRequest\x1a\x1f.fstmon.thermal.ThermalResponseB>Z<github.com/eterline/fstmon/internal/infra/grpc/flugel/commonb\x06proto3"

var (
	file_thermal_proto_rawDescOnce sync.Once
	file_thermal_proto_rawDescData []byte
)

func file_thermal_proto_rawDescGZIP() []byte {
	file_thermal_proto_rawDescOnce.Do(func() {
		file_thermal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thermal_proto_rawDesc), len(file_thermal_proto_rawDesc)))
	})
	return file_thermal_proto_rawDescData
}

var file_thermal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_thermal_proto_goTypes = []any{
	(*ThermalMetrics)(nil),    // 0: fstmon.thermal.ThermalMetrics
	(*ThermalMetricsMap)(nil), // 1: fstmon.thermal.ThermalMetricsMap
	(*GetThermalRequest)(nil), // 2: fstmon.thermal.GetThermalRequest
	(*ThermalResponse)(nil),   // 3: fstmon.thermal.ThermalResponse
	nil,                       // 4: fstmon.thermal.ThermalMetricsMap.SensorsEntry
}
var file_thermal_proto_depIdxs = []int32{
	4, // 0: fstmon.thermal.ThermalMetricsMap.sensors:type_name -> fstmon.thermal.ThermalMetricsMap.SensorsEntry
	1, // 1: fstmon.thermal.ThermalResponse.metrics:type_name -> fstmon.thermal.ThermalMetricsMap
	0, // 2: fstmon.thermal.ThermalMetricsMap.SensorsEntry.value:type_name -> fstmon.thermal.ThermalMetrics
	2, // 3: fstmon.thermal.ThermalService.GetThermal:input_type -> fstmon.thermal.GetThermalRequest
	3, // 4: fstmon.thermal.ThermalService.GetThermal:output_type -> fstmon.thermal.ThermalResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_thermal_proto_init() }
func file_thermal_proto_init() {
	if File_thermal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thermal_proto_rawDesc), len(file_thermal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thermal_proto_goTypes,
		DependencyIndexes: file_thermal_proto_depIdxs,
		MessageInfos:      file_thermal_proto_msgTypes,
	}.Build()
	File_thermal_proto = out.File
	file_thermal_proto_goTypes = nil
	file_thermal_proto_depIdxs = nil
}
