// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: thermal.proto

package common

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThermalService_GetThermal_FullMethodName = "/fstmon.thermal.ThermalService/GetThermal"
)

// ThermalServiceClient is the client API for ThermalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThermalServiceClient interface {
	GetThermal(ctx context.Context, in *GetThermalRequest, opts ...grpc.CallOption) (*ThermalResponse, error)
}

type thermalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThermalServiceClient(cc grpc.ClientConnInterface) ThermalServiceClient {
	return &thermalServiceClient{cc}
}

func (c *thermalServiceClient) GetThermal(ctx context.Context, in *GetThermalRequest, opts ...grpc.CallOption) (*ThermalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThermalResponse)
	err := c.cc.Invoke(ctx, ThermalService_GetThermal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThermalServiceServer is the server API for ThermalService service.
// All implementations must embed UnimplementedThermalServiceServer
// for forward compatibility.
type ThermalServiceServer interface {
	GetThermal(context.Context, *GetThermalRequest) (*ThermalResponse, error)
	mustEmbedUnimplementedThermalServiceServer()
}

// UnimplementedThermalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThermalServiceServer struct{}

func (UnimplementedThermalServiceServer) GetThermal(context.Context, *GetThermalRequest) (*ThermalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThermal not implemented")
}
func (UnimplementedThermalServiceServer) mustEmbedUnimplementedThermalServiceServer() {}
func (UnimplementedThermalServiceServer) testEmbeddedByValue()                        {}

// UnsafeThermalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThermalServiceServer will
// result in compilation errors.
type UnsafeThermalServiceServer interface {
	mustEmbedUnimplementedThermalServiceServer()
}

func RegisterThermalServiceServer(s grpc.ServiceRegistrar, srv ThermalServiceServer) {
	// If the following call panics, it indicates UnimplementedThermalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThermalService_ServiceDesc, srv)
}

func _ThermalService_GetThermal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThermalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThermalServiceServer).GetThermal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThermalService_GetThermal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThermalServiceServer).GetThermal(ctx, req.(*GetThermalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThermalService_ServiceDesc is the grpc.ServiceDesc for ThermalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThermalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fstmon.thermal.ThermalService",
	HandlerType: (*ThermalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThermal",
			Handler:    _ThermalService_GetThermal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thermal.proto",
}
